// Command bootstrap-commands prints a starting commands.yaml derived from the
// spec, to be hand-corrected rather than used as-is.
package main

import (
	"fmt"
	"sort"
	"strings"

	"github.com/flexprice/cli/internal/spec"
)

// verb maps an operationId prefix to the CLI's domain vocabulary.
var verb = []struct{ prefix, action string }{
	{"create", "create"},
	{"update", "update"},
	{"delete", "delete"},
	{"query", "list"}, // POST /x/search is how listing works in this API
	{"list", "list"},
	{"get", "retrieve"},
}

func main() {
	doc, err := spec.Load()
	if err != nil {
		panic(err)
	}

	byResource := map[string]map[string]string{}
	for _, op := range spec.Operations(doc) {
		resource, derived := spec.DeriveName(op.Tag, op.ID)
		action := derived
		for _, v := range verb {
			if strings.HasPrefix(op.ID, v.prefix) {
				action = v.action
				break
			}
		}
		if byResource[resource] == nil {
			byResource[resource] = map[string]string{}
		}
		// On collision keep the first and leave the second under its derived name
		// so a human resolves it rather than the tool silently picking.
		if _, taken := byResource[resource][action]; taken {
			action = derived
		}
		byResource[resource][action] = op.ID
	}

	fmt.Println("# Generated by cli/tools/bootstrap-commands. Hand-correct before committing.")
	fmt.Println("resources:")
	resources := make([]string, 0, len(byResource))
	for r := range byResource {
		resources = append(resources, r)
	}
	sort.Strings(resources)

	for _, r := range resources {
		fmt.Printf("  %s:\n", r)
		actions := make([]string, 0, len(byResource[r]))
		for a := range byResource[r] {
			actions = append(actions, a)
		}
		sort.Strings(actions)
		for _, a := range actions {
			fmt.Printf("    %s: %s\n", a, byResource[r][a])
		}
	}
	fmt.Println("exclude: []")
}
