// Code generated by ent, DO NOT EDIT.

package stripetenantconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldTenantID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldUpdatedBy, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldEnvironmentID, v))
}

// APIKeyEncrypted applies equality check predicate on the "api_key_encrypted" field. It's identical to APIKeyEncryptedEQ.
func APIKeyEncrypted(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldAPIKeyEncrypted, v))
}

// SyncEnabled applies equality check predicate on the "sync_enabled" field. It's identical to SyncEnabledEQ.
func SyncEnabled(v bool) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldSyncEnabled, v))
}

// AggregationWindowMinutes applies equality check predicate on the "aggregation_window_minutes" field. It's identical to AggregationWindowMinutesEQ.
func AggregationWindowMinutes(v int) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldAggregationWindowMinutes, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldContainsFold(FieldTenantID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDGT applies the GT predicate on the "environment_id" field.
func EnvironmentIDGT(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGT(FieldEnvironmentID, v))
}

// EnvironmentIDGTE applies the GTE predicate on the "environment_id" field.
func EnvironmentIDGTE(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGTE(FieldEnvironmentID, v))
}

// EnvironmentIDLT applies the LT predicate on the "environment_id" field.
func EnvironmentIDLT(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLT(FieldEnvironmentID, v))
}

// EnvironmentIDLTE applies the LTE predicate on the "environment_id" field.
func EnvironmentIDLTE(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLTE(FieldEnvironmentID, v))
}

// EnvironmentIDContains applies the Contains predicate on the "environment_id" field.
func EnvironmentIDContains(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldContains(FieldEnvironmentID, v))
}

// EnvironmentIDHasPrefix applies the HasPrefix predicate on the "environment_id" field.
func EnvironmentIDHasPrefix(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldHasPrefix(FieldEnvironmentID, v))
}

// EnvironmentIDHasSuffix applies the HasSuffix predicate on the "environment_id" field.
func EnvironmentIDHasSuffix(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldHasSuffix(FieldEnvironmentID, v))
}

// EnvironmentIDIsNil applies the IsNil predicate on the "environment_id" field.
func EnvironmentIDIsNil() predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldIsNull(FieldEnvironmentID))
}

// EnvironmentIDNotNil applies the NotNil predicate on the "environment_id" field.
func EnvironmentIDNotNil() predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNotNull(FieldEnvironmentID))
}

// EnvironmentIDEqualFold applies the EqualFold predicate on the "environment_id" field.
func EnvironmentIDEqualFold(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEqualFold(FieldEnvironmentID, v))
}

// EnvironmentIDContainsFold applies the ContainsFold predicate on the "environment_id" field.
func EnvironmentIDContainsFold(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldContainsFold(FieldEnvironmentID, v))
}

// APIKeyEncryptedEQ applies the EQ predicate on the "api_key_encrypted" field.
func APIKeyEncryptedEQ(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedNEQ applies the NEQ predicate on the "api_key_encrypted" field.
func APIKeyEncryptedNEQ(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNEQ(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedIn applies the In predicate on the "api_key_encrypted" field.
func APIKeyEncryptedIn(vs ...string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldIn(FieldAPIKeyEncrypted, vs...))
}

// APIKeyEncryptedNotIn applies the NotIn predicate on the "api_key_encrypted" field.
func APIKeyEncryptedNotIn(vs ...string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNotIn(FieldAPIKeyEncrypted, vs...))
}

// APIKeyEncryptedGT applies the GT predicate on the "api_key_encrypted" field.
func APIKeyEncryptedGT(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGT(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedGTE applies the GTE predicate on the "api_key_encrypted" field.
func APIKeyEncryptedGTE(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGTE(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedLT applies the LT predicate on the "api_key_encrypted" field.
func APIKeyEncryptedLT(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLT(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedLTE applies the LTE predicate on the "api_key_encrypted" field.
func APIKeyEncryptedLTE(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLTE(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedContains applies the Contains predicate on the "api_key_encrypted" field.
func APIKeyEncryptedContains(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldContains(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedHasPrefix applies the HasPrefix predicate on the "api_key_encrypted" field.
func APIKeyEncryptedHasPrefix(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldHasPrefix(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedHasSuffix applies the HasSuffix predicate on the "api_key_encrypted" field.
func APIKeyEncryptedHasSuffix(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldHasSuffix(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedEqualFold applies the EqualFold predicate on the "api_key_encrypted" field.
func APIKeyEncryptedEqualFold(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEqualFold(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedContainsFold applies the ContainsFold predicate on the "api_key_encrypted" field.
func APIKeyEncryptedContainsFold(v string) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldContainsFold(FieldAPIKeyEncrypted, v))
}

// SyncEnabledEQ applies the EQ predicate on the "sync_enabled" field.
func SyncEnabledEQ(v bool) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldSyncEnabled, v))
}

// SyncEnabledNEQ applies the NEQ predicate on the "sync_enabled" field.
func SyncEnabledNEQ(v bool) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNEQ(FieldSyncEnabled, v))
}

// AggregationWindowMinutesEQ applies the EQ predicate on the "aggregation_window_minutes" field.
func AggregationWindowMinutesEQ(v int) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldEQ(FieldAggregationWindowMinutes, v))
}

// AggregationWindowMinutesNEQ applies the NEQ predicate on the "aggregation_window_minutes" field.
func AggregationWindowMinutesNEQ(v int) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNEQ(FieldAggregationWindowMinutes, v))
}

// AggregationWindowMinutesIn applies the In predicate on the "aggregation_window_minutes" field.
func AggregationWindowMinutesIn(vs ...int) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldIn(FieldAggregationWindowMinutes, vs...))
}

// AggregationWindowMinutesNotIn applies the NotIn predicate on the "aggregation_window_minutes" field.
func AggregationWindowMinutesNotIn(vs ...int) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNotIn(FieldAggregationWindowMinutes, vs...))
}

// AggregationWindowMinutesGT applies the GT predicate on the "aggregation_window_minutes" field.
func AggregationWindowMinutesGT(v int) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGT(FieldAggregationWindowMinutes, v))
}

// AggregationWindowMinutesGTE applies the GTE predicate on the "aggregation_window_minutes" field.
func AggregationWindowMinutesGTE(v int) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldGTE(FieldAggregationWindowMinutes, v))
}

// AggregationWindowMinutesLT applies the LT predicate on the "aggregation_window_minutes" field.
func AggregationWindowMinutesLT(v int) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLT(FieldAggregationWindowMinutes, v))
}

// AggregationWindowMinutesLTE applies the LTE predicate on the "aggregation_window_minutes" field.
func AggregationWindowMinutesLTE(v int) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldLTE(FieldAggregationWindowMinutes, v))
}

// WebhookConfigIsNil applies the IsNil predicate on the "webhook_config" field.
func WebhookConfigIsNil() predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldIsNull(FieldWebhookConfig))
}

// WebhookConfigNotNil applies the NotNil predicate on the "webhook_config" field.
func WebhookConfigNotNil() predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.FieldNotNull(FieldWebhookConfig))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StripeTenantConfig) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StripeTenantConfig) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StripeTenantConfig) predicate.StripeTenantConfig {
	return predicate.StripeTenantConfig(sql.NotPredicates(p))
}
