#!/usr/bin/env bash
# Draft the next migration from the Ent schema.
#
# Builds a throwaway database from the committed migrations, asks Ent what is still
# missing, and writes that DDL into a new dbmate file. The result is a DRAFT: it has
# no CONCURRENTLY, no lock timeouts, and no lane placement. Review and edit before
# committing.
#
#   ./generate.sh add_currency_to_invoices
set -euo pipefail
NAME="${1:?usage: generate.sh <migration_name>}"
DIR="${MIGRATIONS_PG:-migrations/versioned/postgres}"
PGHOST_="${PGHOST_:-localhost}"; PGPORT_="${PGPORT_:-5440}"
PGUSER_="${PGUSER_:-flexprice}"; PGPASS_="${PGPASS_:-flexprice123}"
BASE="postgres://$PGUSER_:$PGPASS_@$PGHOST_:$PGPORT_"
export PGPASSWORD="$PGPASS_"

psql "$BASE/postgres?sslmode=disable" -q -c "DROP DATABASE IF EXISTS mig_draft;" \
                                     -c "CREATE DATABASE mig_draft;" >/dev/null
DATABASE_URL="$BASE/mig_draft?sslmode=disable" dbmate --migrations-dir "$DIR" --no-dump-schema up >/dev/null

DDL="$(FLEXPRICE_POSTGRES_HOST="$PGHOST_" FLEXPRICE_POSTGRES_PORT="$PGPORT_" \
       FLEXPRICE_POSTGRES_USER="$PGUSER_" FLEXPRICE_POSTGRES_PASSWORD="$PGPASS_" \
       FLEXPRICE_POSTGRES_DBNAME="mig_draft" FLEXPRICE_POSTGRES_SSLMODE="disable" \
       go run ./cmd/migrate postgres --dry-run --allow-index-changes 2>/dev/null | grep -v '^$' || true)"

if [ -z "$DDL" ]; then
  echo "nothing to generate — migrations already cover the Ent schema"
  exit 0
fi

FILE="$DIR/$(date -u +%Y%m%d%H%M%S)_${NAME}.sql"
{
  echo "-- migrate:up"
  echo "-- DRAFT generated by scripts/migrations/generate.sh — review before merging."
  echo "-- Add CONCURRENTLY to index builds, choose the lane, and write the down block."
  echo "SET lock_timeout = '3s';"
  echo "SET statement_timeout = '30s';"
  echo
  echo "$DDL"
  echo
  echo "-- migrate:down"
  echo "-- TODO: write the reversal, or state why it is unsafe."
} > "$FILE"
echo "drafted $FILE"
echo "--- review it ---"
sed -n '1,20p' "$FILE"
