// Code generated by ent, DO NOT EDIT.

package activitylog

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the activitylog type in the database.
	Label = "activity_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldEnvironmentID holds the string denoting the environment_id field in the database.
	FieldEnvironmentID = "environment_id"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldEntityType holds the string denoting the entity_type field in the database.
	FieldEntityType = "entity_type"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldEntityLabel holds the string denoting the entity_label field in the database.
	FieldEntityLabel = "entity_label"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldActorType holds the string denoting the actor_type field in the database.
	FieldActorType = "actor_type"
	// FieldActorID holds the string denoting the actor_id field in the database.
	FieldActorID = "actor_id"
	// FieldActorLabel holds the string denoting the actor_label field in the database.
	FieldActorLabel = "actor_label"
	// FieldActorUserID holds the string denoting the actor_user_id field in the database.
	FieldActorUserID = "actor_user_id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldCustomerID holds the string denoting the customer_id field in the database.
	FieldCustomerID = "customer_id"
	// FieldSubscriptionID holds the string denoting the subscription_id field in the database.
	FieldSubscriptionID = "subscription_id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldOutcome holds the string denoting the outcome field in the database.
	FieldOutcome = "outcome"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldChanges holds the string denoting the changes field in the database.
	FieldChanges = "changes"
	// FieldSnapshot holds the string denoting the snapshot field in the database.
	FieldSnapshot = "snapshot"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldOccurredAt holds the string denoting the occurred_at field in the database.
	FieldOccurredAt = "occurred_at"
	// Table holds the table name of the activitylog in the database.
	Table = "activity_logs"
)

// Columns holds all SQL columns for activitylog fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldEnvironmentID,
	FieldCategory,
	FieldEntityType,
	FieldEntityID,
	FieldEntityLabel,
	FieldAction,
	FieldActorType,
	FieldActorID,
	FieldActorLabel,
	FieldActorUserID,
	FieldSource,
	FieldCustomerID,
	FieldSubscriptionID,
	FieldRequestID,
	FieldOutcome,
	FieldErrorCode,
	FieldChanges,
	FieldSnapshot,
	FieldMetadata,
	FieldOccurredAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCategory holds the default value on creation for the "category" field.
	DefaultCategory string
	// DefaultEntityLabel holds the default value on creation for the "entity_label" field.
	DefaultEntityLabel string
	// DefaultActorLabel holds the default value on creation for the "actor_label" field.
	DefaultActorLabel string
	// DefaultOutcome holds the default value on creation for the "outcome" field.
	DefaultOutcome string
	// DefaultOccurredAt holds the default value on creation for the "occurred_at" field.
	DefaultOccurredAt func() time.Time
)

// OrderOption defines the ordering options for the ActivityLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByEnvironmentID orders the results by the environment_id field.
func ByEnvironmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnvironmentID, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByEntityType orders the results by the entity_type field.
func ByEntityType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityType, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// ByEntityLabel orders the results by the entity_label field.
func ByEntityLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityLabel, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByActorType orders the results by the actor_type field.
func ByActorType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorType, opts...).ToFunc()
}

// ByActorID orders the results by the actor_id field.
func ByActorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorID, opts...).ToFunc()
}

// ByActorLabel orders the results by the actor_label field.
func ByActorLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorLabel, opts...).ToFunc()
}

// ByActorUserID orders the results by the actor_user_id field.
func ByActorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorUserID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByCustomerID orders the results by the customer_id field.
func ByCustomerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerID, opts...).ToFunc()
}

// BySubscriptionID orders the results by the subscription_id field.
func BySubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByOutcome orders the results by the outcome field.
func ByOutcome(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutcome, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByOccurredAt orders the results by the occurred_at field.
func ByOccurredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOccurredAt, opts...).ToFunc()
}
