Using config file: /Users/gursimarsingh/Documents/projects/flexprice/internal/config/config.yaml
DROP INDEX "addon_tenant_id_environment_id_lookup_key";
CREATE UNIQUE INDEX "addon_tenant_id_environment_id_lookup_key" ON "addons" ("tenant_id", "environment_id", "lookup_key") WHERE status = 'published' AND lookup_key IS NOT NULL AND lookup_key != '';
DROP INDEX "idx_auth_user_id_unique";
CREATE UNIQUE INDEX "idx_auth_user_id_unique" ON "auths" ("user_id") WHERE status = 'published';
DROP INDEX "idx_costsheet_tenant_environment_lookup_key";
CREATE UNIQUE INDEX "idx_costsheet_tenant_environment_lookup_key" ON "costsheets" ("tenant_id", "environment_id", "lookup_key") WHERE status = 'published' AND lookup_key IS NOT NULL AND lookup_key != '';
DROP INDEX "idx_coupon_tenant_environment_coupon_code_unique";
CREATE UNIQUE INDEX "idx_coupon_tenant_environment_coupon_code_unique" ON "coupons" ("tenant_id", "environment_id", "coupon_code") WHERE coupon_code IS NOT NULL AND coupon_code != '' AND status = 'published';
DROP INDEX "creditnote_tenant_id_environment_id_idempotency_key";
DROP INDEX "idx_tenant_environment_credit_note_number_unique";
CREATE INDEX "creditnote_tenant_id_environment_id_idempotency_key" ON "credit_notes" ("tenant_id", "environment_id", "idempotency_key") WHERE idempotency_key IS NOT NULL AND idempotency_key != '';
CREATE UNIQUE INDEX "idx_tenant_environment_credit_note_number_unique" ON "credit_notes" ("tenant_id", "environment_id", "credit_note_number") WHERE credit_note_number IS NOT NULL AND credit_note_number != '' AND status = 'published';
DROP INDEX "idx_customer_tenant_environment_email";
DROP INDEX "idx_tenant_environment_external_id_unique";
CREATE INDEX "idx_customer_tenant_environment_email" ON "customers" ("tenant_id", "environment_id", "email") WHERE email IS NOT NULL AND email != '' AND status = 'published';
CREATE UNIQUE INDEX "idx_tenant_environment_external_id_unique" ON "customers" ("tenant_id", "environment_id", "external_id") WHERE (external_id IS NOT NULL AND external_id != '') AND status = 'published';
DROP INDEX "entitlement_entity_id_entity_t_24e490ce36f12474ef30194a8dd3e18d";
DROP INDEX "entitlement_tenant_id_environm_4be9d447f26ab17e315682af3a45d8ea";
CREATE INDEX "entitlement_entity_id_entity_t_24e490ce36f12474ef30194a8dd3e18d" ON "entitlements" ("entity_id", "entity_type", "feature_id", "start_date", "end_date") WHERE entity_type = 'SUBSCRIPTION' AND status = 'published';
CREATE UNIQUE INDEX "entitlement_tenant_id_environm_4be9d447f26ab17e315682af3a45d8ea" ON "entitlements" ("tenant_id", "environment_id", "entity_type", "entity_id", "feature_id") WHERE status = 'published';
DROP INDEX "idx_entity_integration_mapping_unique";
CREATE UNIQUE INDEX "idx_entity_integration_mapping_unique" ON "entity_integration_mappings" ("tenant_id", "environment_id", "entity_type", "entity_id", "provider_type") WHERE status = 'published';
DROP INDEX "idx_feature_tenant_env_lookup_key_unique";
CREATE UNIQUE INDEX "idx_feature_tenant_env_lookup_key_unique" ON "features" ("tenant_id", "environment_id", "lookup_key") WHERE (lookup_key IS NOT NULL AND lookup_key != '') AND status = 'published';
DROP INDEX "idx_group_tenant_environment_lookup_key";
CREATE UNIQUE INDEX "idx_group_tenant_environment_lookup_key" ON "groups" ("tenant_id", "environment_id", "lookup_key") WHERE status = 'published' AND lookup_key IS NOT NULL AND lookup_key != '';
DROP INDEX "idx_subscription_period_unique";
DROP INDEX "idx_tenant_customer_status";
DROP INDEX "idx_tenant_environment_invoice_number_unique";
CREATE INDEX "idx_subscription_period_unique" ON "invoices" ("subscription_id", "period_start", "period_end") WHERE invoice_status != 'VOIDED' AND subscription_id IS NOT NULL;
CREATE INDEX "idx_tenant_customer_status" ON "invoices" ("tenant_id", "environment_id", "customer_id", "invoice_status", "payment_status", "status") WHERE status = 'published';
CREATE UNIQUE INDEX "idx_tenant_environment_invoice_number_unique" ON "invoices" ("tenant_id", "environment_id", "invoice_number") WHERE invoice_number IS NOT NULL AND invoice_number != '' AND status = 'published';
DROP INDEX "idx_tenant_gateway_payment";
CREATE INDEX "idx_tenant_gateway_payment" ON "payments" ("tenant_id", "environment_id", "payment_gateway", "gateway_payment_id") WHERE payment_gateway IS NOT NULL AND gateway_payment_id IS NOT NULL;
DROP INDEX "idx_tenant_environment_lookup_key";
CREATE UNIQUE INDEX "idx_tenant_environment_lookup_key" ON "plans" ("tenant_id", "environment_id", "lookup_key") WHERE status = 'published' AND lookup_key IS NOT NULL AND lookup_key != '';
DROP INDEX "priceunit_tenant_id_environment_id_code";
CREATE UNIQUE INDEX "priceunit_tenant_id_environment_id_code" ON "price_units" ("tenant_id", "environment_id", "code") WHERE status = 'published';
DROP INDEX "price_tenant_id_environment_id_entity_id_entity_type_sequence";
DROP INDEX "price_tenant_id_environment_id_lookup_key";
CREATE INDEX "price_tenant_id_environment_id_entity_id_entity_type_sequence" ON "prices" ("tenant_id", "environment_id", "entity_id", "entity_type", "sequence") WHERE status = 'published';
CREATE UNIQUE INDEX "price_tenant_id_environment_id_lookup_key" ON "prices" ("tenant_id", "environment_id", "lookup_key") WHERE status = 'published' AND lookup_key IS NOT NULL AND lookup_key != '' AND end_date IS NULL;
DROP INDEX "subscriptionschedule_scheduled_at_status";
DROP INDEX "subscriptionschedule_status_schedule_type";
DROP INDEX "subscriptionschedule_subscription_id_schedule_type";
CREATE INDEX "subscriptionschedule_scheduled_at_status" ON "subscription_schedules" ("scheduled_at", "status") WHERE status = 'pending';
CREATE INDEX "subscriptionschedule_status_schedule_type" ON "subscription_schedules" ("status", "schedule_type") WHERE status = 'pending';
CREATE UNIQUE INDEX "subscriptionschedule_subscription_id_schedule_type" ON "subscription_schedules" ("subscription_id", "schedule_type") WHERE status = 'pending';
DROP INDEX "subscription_tenant_id_environ_0ad331316983221cbcb024161ce97770";
DROP INDEX "subscription_tenant_id_environment_id_customer_id_status";
CREATE INDEX "subscription_tenant_id_environ_0ad331316983221cbcb024161ce97770" ON "subscriptions" ("tenant_id", "environment_id", "plan_id", "synced_price_sequence") WHERE status = 'published' AND subscription_type IN ('standalone','delegated_invoicing','parent','grouped_invoicing');
CREATE INDEX "subscription_tenant_id_environment_id_customer_id_status" ON "subscriptions" ("tenant_id", "environment_id", "customer_id", "status") WHERE status = 'published';
DROP INDEX "idx_code_tenant_id_environment_id";
CREATE UNIQUE INDEX "idx_code_tenant_id_environment_id" ON "tax_rates" ("tenant_id", "environment_id", "code") WHERE (code IS NOT NULL AND code != '' and status = 'published');
DROP INDEX "idx_user_email_unique";
CREATE UNIQUE INDEX "idx_user_email_unique" ON "users" ("email") WHERE status = 'published' AND email IS NOT NULL AND email != '';
DROP INDEX "idx_tenant_environment_idempotency_key";
DROP INDEX "idx_tenant_wallet_type_credits_available_expiry_date";
CREATE UNIQUE INDEX "idx_tenant_environment_idempotency_key" ON "wallet_transactions" ("tenant_id", "environment_id", "idempotency_key") WHERE idempotency_key IS NOT NULL AND idempotency_key <> '' AND status='published';
CREATE INDEX "idx_tenant_wallet_type_credits_available_expiry_date" ON "wallet_transactions" ("tenant_id", "environment_id", "wallet_id", "type", "credits_available", "expiry_date") WHERE credits_available > 0 AND type = 'credit';
CREATE TABLE "webhook_requests" ("id" character varying(50) NOT NULL, "tenant_id" character varying(50) NOT NULL, "environment_id" character varying(50) NOT NULL, "provider" character varying(50) NOT NULL, "method" character varying(10) NOT NULL, "path" text NOT NULL, "request_id" character varying(100) NULL, "headers" jsonb NULL, "body" text NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
CREATE INDEX "idx_webhook_requests_tenant_env" ON "webhook_requests" ("tenant_id", "environment_id");
CREATE INDEX "idx_webhook_requests_provider" ON "webhook_requests" ("provider");
CREATE INDEX "idx_webhook_requests_request_id" ON "webhook_requests" ("request_id");
CREATE INDEX "idx_webhook_requests_created_at" ON "webhook_requests" ("created_at");
Migration process completed
