// Code generated by ent, DO NOT EDIT.

package checkout

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/internal/types"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldTenantID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldUpdatedBy, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldEnvironmentID, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCustomerID, v))
}

// EntityType applies equality check predicate on the "entity_type" field. It's identical to EntityTypeEQ.
func EntityType(v types.CheckoutEntityType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldEQ(FieldEntityType, vc))
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldEntityID, v))
}

// SourceSubscriptionID applies equality check predicate on the "source_subscription_id" field. It's identical to SourceSubscriptionIDEQ.
func SourceSubscriptionID(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldSourceSubscriptionID, v))
}

// CheckoutType applies equality check predicate on the "checkout_type" field. It's identical to CheckoutTypeEQ.
func CheckoutType(v types.CheckoutType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldEQ(FieldCheckoutType, vc))
}

// Objective applies equality check predicate on the "objective" field. It's identical to ObjectiveEQ.
func Objective(v types.CheckoutObjective) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldEQ(FieldObjective, vc))
}

// CheckoutStatus applies equality check predicate on the "checkout_status" field. It's identical to CheckoutStatusEQ.
func CheckoutStatus(v types.CheckoutStatus) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldEQ(FieldCheckoutStatus, vc))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v decimal.Decimal) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCurrency, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldProvider, v))
}

// ProviderSessionID applies equality check predicate on the "provider_session_id" field. It's identical to ProviderSessionIDEQ.
func ProviderSessionID(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldProviderSessionID, v))
}

// CheckoutURL applies equality check predicate on the "checkout_url" field. It's identical to CheckoutURLEQ.
func CheckoutURL(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCheckoutURL, v))
}

// SuccessURL applies equality check predicate on the "success_url" field. It's identical to SuccessURLEQ.
func SuccessURL(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldSuccessURL, v))
}

// CancelURL applies equality check predicate on the "cancel_url" field. It's identical to CancelURLEQ.
func CancelURL(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCancelURL, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldExpiresAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCompletedAt, v))
}

// CancelledAt applies equality check predicate on the "cancelled_at" field. It's identical to CancelledAtEQ.
func CancelledAt(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCancelledAt, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldErrorMessage, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldTenantID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDGT applies the GT predicate on the "environment_id" field.
func EnvironmentIDGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldEnvironmentID, v))
}

// EnvironmentIDGTE applies the GTE predicate on the "environment_id" field.
func EnvironmentIDGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldEnvironmentID, v))
}

// EnvironmentIDLT applies the LT predicate on the "environment_id" field.
func EnvironmentIDLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldEnvironmentID, v))
}

// EnvironmentIDLTE applies the LTE predicate on the "environment_id" field.
func EnvironmentIDLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldEnvironmentID, v))
}

// EnvironmentIDContains applies the Contains predicate on the "environment_id" field.
func EnvironmentIDContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldEnvironmentID, v))
}

// EnvironmentIDHasPrefix applies the HasPrefix predicate on the "environment_id" field.
func EnvironmentIDHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldEnvironmentID, v))
}

// EnvironmentIDHasSuffix applies the HasSuffix predicate on the "environment_id" field.
func EnvironmentIDHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldEnvironmentID, v))
}

// EnvironmentIDIsNil applies the IsNil predicate on the "environment_id" field.
func EnvironmentIDIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldEnvironmentID))
}

// EnvironmentIDNotNil applies the NotNil predicate on the "environment_id" field.
func EnvironmentIDNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldEnvironmentID))
}

// EnvironmentIDEqualFold applies the EqualFold predicate on the "environment_id" field.
func EnvironmentIDEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldEnvironmentID, v))
}

// EnvironmentIDContainsFold applies the ContainsFold predicate on the "environment_id" field.
func EnvironmentIDContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldEnvironmentID, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldCustomerID, v))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldCustomerID, v))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldCustomerID, v))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldCustomerID, v))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldCustomerID, v))
}

// EntityTypeEQ applies the EQ predicate on the "entity_type" field.
func EntityTypeEQ(v types.CheckoutEntityType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldEQ(FieldEntityType, vc))
}

// EntityTypeNEQ applies the NEQ predicate on the "entity_type" field.
func EntityTypeNEQ(v types.CheckoutEntityType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldNEQ(FieldEntityType, vc))
}

// EntityTypeIn applies the In predicate on the "entity_type" field.
func EntityTypeIn(vs ...types.CheckoutEntityType) predicate.Checkout {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Checkout(sql.FieldIn(FieldEntityType, v...))
}

// EntityTypeNotIn applies the NotIn predicate on the "entity_type" field.
func EntityTypeNotIn(vs ...types.CheckoutEntityType) predicate.Checkout {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Checkout(sql.FieldNotIn(FieldEntityType, v...))
}

// EntityTypeGT applies the GT predicate on the "entity_type" field.
func EntityTypeGT(v types.CheckoutEntityType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldGT(FieldEntityType, vc))
}

// EntityTypeGTE applies the GTE predicate on the "entity_type" field.
func EntityTypeGTE(v types.CheckoutEntityType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldGTE(FieldEntityType, vc))
}

// EntityTypeLT applies the LT predicate on the "entity_type" field.
func EntityTypeLT(v types.CheckoutEntityType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldLT(FieldEntityType, vc))
}

// EntityTypeLTE applies the LTE predicate on the "entity_type" field.
func EntityTypeLTE(v types.CheckoutEntityType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldLTE(FieldEntityType, vc))
}

// EntityTypeContains applies the Contains predicate on the "entity_type" field.
func EntityTypeContains(v types.CheckoutEntityType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldContains(FieldEntityType, vc))
}

// EntityTypeHasPrefix applies the HasPrefix predicate on the "entity_type" field.
func EntityTypeHasPrefix(v types.CheckoutEntityType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldHasPrefix(FieldEntityType, vc))
}

// EntityTypeHasSuffix applies the HasSuffix predicate on the "entity_type" field.
func EntityTypeHasSuffix(v types.CheckoutEntityType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldHasSuffix(FieldEntityType, vc))
}

// EntityTypeEqualFold applies the EqualFold predicate on the "entity_type" field.
func EntityTypeEqualFold(v types.CheckoutEntityType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldEqualFold(FieldEntityType, vc))
}

// EntityTypeContainsFold applies the ContainsFold predicate on the "entity_type" field.
func EntityTypeContainsFold(v types.CheckoutEntityType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldContainsFold(FieldEntityType, vc))
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldEntityID, v))
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldEntityID, v))
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldEntityID, vs...))
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldEntityID, vs...))
}

// EntityIDGT applies the GT predicate on the "entity_id" field.
func EntityIDGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldEntityID, v))
}

// EntityIDGTE applies the GTE predicate on the "entity_id" field.
func EntityIDGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldEntityID, v))
}

// EntityIDLT applies the LT predicate on the "entity_id" field.
func EntityIDLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldEntityID, v))
}

// EntityIDLTE applies the LTE predicate on the "entity_id" field.
func EntityIDLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldEntityID, v))
}

// EntityIDContains applies the Contains predicate on the "entity_id" field.
func EntityIDContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldEntityID, v))
}

// EntityIDHasPrefix applies the HasPrefix predicate on the "entity_id" field.
func EntityIDHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldEntityID, v))
}

// EntityIDHasSuffix applies the HasSuffix predicate on the "entity_id" field.
func EntityIDHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldEntityID, v))
}

// EntityIDEqualFold applies the EqualFold predicate on the "entity_id" field.
func EntityIDEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldEntityID, v))
}

// EntityIDContainsFold applies the ContainsFold predicate on the "entity_id" field.
func EntityIDContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldEntityID, v))
}

// SourceSubscriptionIDEQ applies the EQ predicate on the "source_subscription_id" field.
func SourceSubscriptionIDEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldSourceSubscriptionID, v))
}

// SourceSubscriptionIDNEQ applies the NEQ predicate on the "source_subscription_id" field.
func SourceSubscriptionIDNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldSourceSubscriptionID, v))
}

// SourceSubscriptionIDIn applies the In predicate on the "source_subscription_id" field.
func SourceSubscriptionIDIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldSourceSubscriptionID, vs...))
}

// SourceSubscriptionIDNotIn applies the NotIn predicate on the "source_subscription_id" field.
func SourceSubscriptionIDNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldSourceSubscriptionID, vs...))
}

// SourceSubscriptionIDGT applies the GT predicate on the "source_subscription_id" field.
func SourceSubscriptionIDGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldSourceSubscriptionID, v))
}

// SourceSubscriptionIDGTE applies the GTE predicate on the "source_subscription_id" field.
func SourceSubscriptionIDGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldSourceSubscriptionID, v))
}

// SourceSubscriptionIDLT applies the LT predicate on the "source_subscription_id" field.
func SourceSubscriptionIDLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldSourceSubscriptionID, v))
}

// SourceSubscriptionIDLTE applies the LTE predicate on the "source_subscription_id" field.
func SourceSubscriptionIDLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldSourceSubscriptionID, v))
}

// SourceSubscriptionIDContains applies the Contains predicate on the "source_subscription_id" field.
func SourceSubscriptionIDContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldSourceSubscriptionID, v))
}

// SourceSubscriptionIDHasPrefix applies the HasPrefix predicate on the "source_subscription_id" field.
func SourceSubscriptionIDHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldSourceSubscriptionID, v))
}

// SourceSubscriptionIDHasSuffix applies the HasSuffix predicate on the "source_subscription_id" field.
func SourceSubscriptionIDHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldSourceSubscriptionID, v))
}

// SourceSubscriptionIDIsNil applies the IsNil predicate on the "source_subscription_id" field.
func SourceSubscriptionIDIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldSourceSubscriptionID))
}

// SourceSubscriptionIDNotNil applies the NotNil predicate on the "source_subscription_id" field.
func SourceSubscriptionIDNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldSourceSubscriptionID))
}

// SourceSubscriptionIDEqualFold applies the EqualFold predicate on the "source_subscription_id" field.
func SourceSubscriptionIDEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldSourceSubscriptionID, v))
}

// SourceSubscriptionIDContainsFold applies the ContainsFold predicate on the "source_subscription_id" field.
func SourceSubscriptionIDContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldSourceSubscriptionID, v))
}

// CheckoutTypeEQ applies the EQ predicate on the "checkout_type" field.
func CheckoutTypeEQ(v types.CheckoutType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldEQ(FieldCheckoutType, vc))
}

// CheckoutTypeNEQ applies the NEQ predicate on the "checkout_type" field.
func CheckoutTypeNEQ(v types.CheckoutType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldNEQ(FieldCheckoutType, vc))
}

// CheckoutTypeIn applies the In predicate on the "checkout_type" field.
func CheckoutTypeIn(vs ...types.CheckoutType) predicate.Checkout {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Checkout(sql.FieldIn(FieldCheckoutType, v...))
}

// CheckoutTypeNotIn applies the NotIn predicate on the "checkout_type" field.
func CheckoutTypeNotIn(vs ...types.CheckoutType) predicate.Checkout {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Checkout(sql.FieldNotIn(FieldCheckoutType, v...))
}

// CheckoutTypeGT applies the GT predicate on the "checkout_type" field.
func CheckoutTypeGT(v types.CheckoutType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldGT(FieldCheckoutType, vc))
}

// CheckoutTypeGTE applies the GTE predicate on the "checkout_type" field.
func CheckoutTypeGTE(v types.CheckoutType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldGTE(FieldCheckoutType, vc))
}

// CheckoutTypeLT applies the LT predicate on the "checkout_type" field.
func CheckoutTypeLT(v types.CheckoutType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldLT(FieldCheckoutType, vc))
}

// CheckoutTypeLTE applies the LTE predicate on the "checkout_type" field.
func CheckoutTypeLTE(v types.CheckoutType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldLTE(FieldCheckoutType, vc))
}

// CheckoutTypeContains applies the Contains predicate on the "checkout_type" field.
func CheckoutTypeContains(v types.CheckoutType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldContains(FieldCheckoutType, vc))
}

// CheckoutTypeHasPrefix applies the HasPrefix predicate on the "checkout_type" field.
func CheckoutTypeHasPrefix(v types.CheckoutType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldHasPrefix(FieldCheckoutType, vc))
}

// CheckoutTypeHasSuffix applies the HasSuffix predicate on the "checkout_type" field.
func CheckoutTypeHasSuffix(v types.CheckoutType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldHasSuffix(FieldCheckoutType, vc))
}

// CheckoutTypeEqualFold applies the EqualFold predicate on the "checkout_type" field.
func CheckoutTypeEqualFold(v types.CheckoutType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldEqualFold(FieldCheckoutType, vc))
}

// CheckoutTypeContainsFold applies the ContainsFold predicate on the "checkout_type" field.
func CheckoutTypeContainsFold(v types.CheckoutType) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldContainsFold(FieldCheckoutType, vc))
}

// ObjectiveEQ applies the EQ predicate on the "objective" field.
func ObjectiveEQ(v types.CheckoutObjective) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldEQ(FieldObjective, vc))
}

// ObjectiveNEQ applies the NEQ predicate on the "objective" field.
func ObjectiveNEQ(v types.CheckoutObjective) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldNEQ(FieldObjective, vc))
}

// ObjectiveIn applies the In predicate on the "objective" field.
func ObjectiveIn(vs ...types.CheckoutObjective) predicate.Checkout {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Checkout(sql.FieldIn(FieldObjective, v...))
}

// ObjectiveNotIn applies the NotIn predicate on the "objective" field.
func ObjectiveNotIn(vs ...types.CheckoutObjective) predicate.Checkout {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Checkout(sql.FieldNotIn(FieldObjective, v...))
}

// ObjectiveGT applies the GT predicate on the "objective" field.
func ObjectiveGT(v types.CheckoutObjective) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldGT(FieldObjective, vc))
}

// ObjectiveGTE applies the GTE predicate on the "objective" field.
func ObjectiveGTE(v types.CheckoutObjective) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldGTE(FieldObjective, vc))
}

// ObjectiveLT applies the LT predicate on the "objective" field.
func ObjectiveLT(v types.CheckoutObjective) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldLT(FieldObjective, vc))
}

// ObjectiveLTE applies the LTE predicate on the "objective" field.
func ObjectiveLTE(v types.CheckoutObjective) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldLTE(FieldObjective, vc))
}

// ObjectiveContains applies the Contains predicate on the "objective" field.
func ObjectiveContains(v types.CheckoutObjective) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldContains(FieldObjective, vc))
}

// ObjectiveHasPrefix applies the HasPrefix predicate on the "objective" field.
func ObjectiveHasPrefix(v types.CheckoutObjective) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldHasPrefix(FieldObjective, vc))
}

// ObjectiveHasSuffix applies the HasSuffix predicate on the "objective" field.
func ObjectiveHasSuffix(v types.CheckoutObjective) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldHasSuffix(FieldObjective, vc))
}

// ObjectiveEqualFold applies the EqualFold predicate on the "objective" field.
func ObjectiveEqualFold(v types.CheckoutObjective) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldEqualFold(FieldObjective, vc))
}

// ObjectiveContainsFold applies the ContainsFold predicate on the "objective" field.
func ObjectiveContainsFold(v types.CheckoutObjective) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldContainsFold(FieldObjective, vc))
}

// CheckoutStatusEQ applies the EQ predicate on the "checkout_status" field.
func CheckoutStatusEQ(v types.CheckoutStatus) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldEQ(FieldCheckoutStatus, vc))
}

// CheckoutStatusNEQ applies the NEQ predicate on the "checkout_status" field.
func CheckoutStatusNEQ(v types.CheckoutStatus) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldNEQ(FieldCheckoutStatus, vc))
}

// CheckoutStatusIn applies the In predicate on the "checkout_status" field.
func CheckoutStatusIn(vs ...types.CheckoutStatus) predicate.Checkout {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Checkout(sql.FieldIn(FieldCheckoutStatus, v...))
}

// CheckoutStatusNotIn applies the NotIn predicate on the "checkout_status" field.
func CheckoutStatusNotIn(vs ...types.CheckoutStatus) predicate.Checkout {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Checkout(sql.FieldNotIn(FieldCheckoutStatus, v...))
}

// CheckoutStatusGT applies the GT predicate on the "checkout_status" field.
func CheckoutStatusGT(v types.CheckoutStatus) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldGT(FieldCheckoutStatus, vc))
}

// CheckoutStatusGTE applies the GTE predicate on the "checkout_status" field.
func CheckoutStatusGTE(v types.CheckoutStatus) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldGTE(FieldCheckoutStatus, vc))
}

// CheckoutStatusLT applies the LT predicate on the "checkout_status" field.
func CheckoutStatusLT(v types.CheckoutStatus) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldLT(FieldCheckoutStatus, vc))
}

// CheckoutStatusLTE applies the LTE predicate on the "checkout_status" field.
func CheckoutStatusLTE(v types.CheckoutStatus) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldLTE(FieldCheckoutStatus, vc))
}

// CheckoutStatusContains applies the Contains predicate on the "checkout_status" field.
func CheckoutStatusContains(v types.CheckoutStatus) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldContains(FieldCheckoutStatus, vc))
}

// CheckoutStatusHasPrefix applies the HasPrefix predicate on the "checkout_status" field.
func CheckoutStatusHasPrefix(v types.CheckoutStatus) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldHasPrefix(FieldCheckoutStatus, vc))
}

// CheckoutStatusHasSuffix applies the HasSuffix predicate on the "checkout_status" field.
func CheckoutStatusHasSuffix(v types.CheckoutStatus) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldHasSuffix(FieldCheckoutStatus, vc))
}

// CheckoutStatusEqualFold applies the EqualFold predicate on the "checkout_status" field.
func CheckoutStatusEqualFold(v types.CheckoutStatus) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldEqualFold(FieldCheckoutStatus, vc))
}

// CheckoutStatusContainsFold applies the ContainsFold predicate on the "checkout_status" field.
func CheckoutStatusContainsFold(v types.CheckoutStatus) predicate.Checkout {
	vc := string(v)
	return predicate.Checkout(sql.FieldContainsFold(FieldCheckoutStatus, vc))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v decimal.Decimal) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v decimal.Decimal) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...decimal.Decimal) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...decimal.Decimal) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v decimal.Decimal) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v decimal.Decimal) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v decimal.Decimal) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v decimal.Decimal) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldAmount, v))
}

// AmountIsNil applies the IsNil predicate on the "amount" field.
func AmountIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldAmount))
}

// AmountNotNil applies the NotNil predicate on the "amount" field.
func AmountNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldAmount))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyIsNil applies the IsNil predicate on the "currency" field.
func CurrencyIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldCurrency))
}

// CurrencyNotNil applies the NotNil predicate on the "currency" field.
func CurrencyNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldCurrency))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldCurrency, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldProvider, v))
}

// ProviderSessionIDEQ applies the EQ predicate on the "provider_session_id" field.
func ProviderSessionIDEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldProviderSessionID, v))
}

// ProviderSessionIDNEQ applies the NEQ predicate on the "provider_session_id" field.
func ProviderSessionIDNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldProviderSessionID, v))
}

// ProviderSessionIDIn applies the In predicate on the "provider_session_id" field.
func ProviderSessionIDIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldProviderSessionID, vs...))
}

// ProviderSessionIDNotIn applies the NotIn predicate on the "provider_session_id" field.
func ProviderSessionIDNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldProviderSessionID, vs...))
}

// ProviderSessionIDGT applies the GT predicate on the "provider_session_id" field.
func ProviderSessionIDGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldProviderSessionID, v))
}

// ProviderSessionIDGTE applies the GTE predicate on the "provider_session_id" field.
func ProviderSessionIDGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldProviderSessionID, v))
}

// ProviderSessionIDLT applies the LT predicate on the "provider_session_id" field.
func ProviderSessionIDLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldProviderSessionID, v))
}

// ProviderSessionIDLTE applies the LTE predicate on the "provider_session_id" field.
func ProviderSessionIDLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldProviderSessionID, v))
}

// ProviderSessionIDContains applies the Contains predicate on the "provider_session_id" field.
func ProviderSessionIDContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldProviderSessionID, v))
}

// ProviderSessionIDHasPrefix applies the HasPrefix predicate on the "provider_session_id" field.
func ProviderSessionIDHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldProviderSessionID, v))
}

// ProviderSessionIDHasSuffix applies the HasSuffix predicate on the "provider_session_id" field.
func ProviderSessionIDHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldProviderSessionID, v))
}

// ProviderSessionIDIsNil applies the IsNil predicate on the "provider_session_id" field.
func ProviderSessionIDIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldProviderSessionID))
}

// ProviderSessionIDNotNil applies the NotNil predicate on the "provider_session_id" field.
func ProviderSessionIDNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldProviderSessionID))
}

// ProviderSessionIDEqualFold applies the EqualFold predicate on the "provider_session_id" field.
func ProviderSessionIDEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldProviderSessionID, v))
}

// ProviderSessionIDContainsFold applies the ContainsFold predicate on the "provider_session_id" field.
func ProviderSessionIDContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldProviderSessionID, v))
}

// CheckoutURLEQ applies the EQ predicate on the "checkout_url" field.
func CheckoutURLEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCheckoutURL, v))
}

// CheckoutURLNEQ applies the NEQ predicate on the "checkout_url" field.
func CheckoutURLNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldCheckoutURL, v))
}

// CheckoutURLIn applies the In predicate on the "checkout_url" field.
func CheckoutURLIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldCheckoutURL, vs...))
}

// CheckoutURLNotIn applies the NotIn predicate on the "checkout_url" field.
func CheckoutURLNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldCheckoutURL, vs...))
}

// CheckoutURLGT applies the GT predicate on the "checkout_url" field.
func CheckoutURLGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldCheckoutURL, v))
}

// CheckoutURLGTE applies the GTE predicate on the "checkout_url" field.
func CheckoutURLGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldCheckoutURL, v))
}

// CheckoutURLLT applies the LT predicate on the "checkout_url" field.
func CheckoutURLLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldCheckoutURL, v))
}

// CheckoutURLLTE applies the LTE predicate on the "checkout_url" field.
func CheckoutURLLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldCheckoutURL, v))
}

// CheckoutURLContains applies the Contains predicate on the "checkout_url" field.
func CheckoutURLContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldCheckoutURL, v))
}

// CheckoutURLHasPrefix applies the HasPrefix predicate on the "checkout_url" field.
func CheckoutURLHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldCheckoutURL, v))
}

// CheckoutURLHasSuffix applies the HasSuffix predicate on the "checkout_url" field.
func CheckoutURLHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldCheckoutURL, v))
}

// CheckoutURLIsNil applies the IsNil predicate on the "checkout_url" field.
func CheckoutURLIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldCheckoutURL))
}

// CheckoutURLNotNil applies the NotNil predicate on the "checkout_url" field.
func CheckoutURLNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldCheckoutURL))
}

// CheckoutURLEqualFold applies the EqualFold predicate on the "checkout_url" field.
func CheckoutURLEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldCheckoutURL, v))
}

// CheckoutURLContainsFold applies the ContainsFold predicate on the "checkout_url" field.
func CheckoutURLContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldCheckoutURL, v))
}

// SuccessURLEQ applies the EQ predicate on the "success_url" field.
func SuccessURLEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldSuccessURL, v))
}

// SuccessURLNEQ applies the NEQ predicate on the "success_url" field.
func SuccessURLNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldSuccessURL, v))
}

// SuccessURLIn applies the In predicate on the "success_url" field.
func SuccessURLIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldSuccessURL, vs...))
}

// SuccessURLNotIn applies the NotIn predicate on the "success_url" field.
func SuccessURLNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldSuccessURL, vs...))
}

// SuccessURLGT applies the GT predicate on the "success_url" field.
func SuccessURLGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldSuccessURL, v))
}

// SuccessURLGTE applies the GTE predicate on the "success_url" field.
func SuccessURLGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldSuccessURL, v))
}

// SuccessURLLT applies the LT predicate on the "success_url" field.
func SuccessURLLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldSuccessURL, v))
}

// SuccessURLLTE applies the LTE predicate on the "success_url" field.
func SuccessURLLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldSuccessURL, v))
}

// SuccessURLContains applies the Contains predicate on the "success_url" field.
func SuccessURLContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldSuccessURL, v))
}

// SuccessURLHasPrefix applies the HasPrefix predicate on the "success_url" field.
func SuccessURLHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldSuccessURL, v))
}

// SuccessURLHasSuffix applies the HasSuffix predicate on the "success_url" field.
func SuccessURLHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldSuccessURL, v))
}

// SuccessURLIsNil applies the IsNil predicate on the "success_url" field.
func SuccessURLIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldSuccessURL))
}

// SuccessURLNotNil applies the NotNil predicate on the "success_url" field.
func SuccessURLNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldSuccessURL))
}

// SuccessURLEqualFold applies the EqualFold predicate on the "success_url" field.
func SuccessURLEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldSuccessURL, v))
}

// SuccessURLContainsFold applies the ContainsFold predicate on the "success_url" field.
func SuccessURLContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldSuccessURL, v))
}

// CancelURLEQ applies the EQ predicate on the "cancel_url" field.
func CancelURLEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCancelURL, v))
}

// CancelURLNEQ applies the NEQ predicate on the "cancel_url" field.
func CancelURLNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldCancelURL, v))
}

// CancelURLIn applies the In predicate on the "cancel_url" field.
func CancelURLIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldCancelURL, vs...))
}

// CancelURLNotIn applies the NotIn predicate on the "cancel_url" field.
func CancelURLNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldCancelURL, vs...))
}

// CancelURLGT applies the GT predicate on the "cancel_url" field.
func CancelURLGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldCancelURL, v))
}

// CancelURLGTE applies the GTE predicate on the "cancel_url" field.
func CancelURLGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldCancelURL, v))
}

// CancelURLLT applies the LT predicate on the "cancel_url" field.
func CancelURLLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldCancelURL, v))
}

// CancelURLLTE applies the LTE predicate on the "cancel_url" field.
func CancelURLLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldCancelURL, v))
}

// CancelURLContains applies the Contains predicate on the "cancel_url" field.
func CancelURLContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldCancelURL, v))
}

// CancelURLHasPrefix applies the HasPrefix predicate on the "cancel_url" field.
func CancelURLHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldCancelURL, v))
}

// CancelURLHasSuffix applies the HasSuffix predicate on the "cancel_url" field.
func CancelURLHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldCancelURL, v))
}

// CancelURLIsNil applies the IsNil predicate on the "cancel_url" field.
func CancelURLIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldCancelURL))
}

// CancelURLNotNil applies the NotNil predicate on the "cancel_url" field.
func CancelURLNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldCancelURL))
}

// CancelURLEqualFold applies the EqualFold predicate on the "cancel_url" field.
func CancelURLEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldCancelURL, v))
}

// CancelURLContainsFold applies the ContainsFold predicate on the "cancel_url" field.
func CancelURLContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldCancelURL, v))
}

// ConfigurationIsNil applies the IsNil predicate on the "configuration" field.
func ConfigurationIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldConfiguration))
}

// ConfigurationNotNil applies the NotNil predicate on the "configuration" field.
func ConfigurationNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldConfiguration))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldExpiresAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldCompletedAt))
}

// CancelledAtEQ applies the EQ predicate on the "cancelled_at" field.
func CancelledAtEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCancelledAt, v))
}

// CancelledAtNEQ applies the NEQ predicate on the "cancelled_at" field.
func CancelledAtNEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldCancelledAt, v))
}

// CancelledAtIn applies the In predicate on the "cancelled_at" field.
func CancelledAtIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldCancelledAt, vs...))
}

// CancelledAtNotIn applies the NotIn predicate on the "cancelled_at" field.
func CancelledAtNotIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldCancelledAt, vs...))
}

// CancelledAtGT applies the GT predicate on the "cancelled_at" field.
func CancelledAtGT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldCancelledAt, v))
}

// CancelledAtGTE applies the GTE predicate on the "cancelled_at" field.
func CancelledAtGTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldCancelledAt, v))
}

// CancelledAtLT applies the LT predicate on the "cancelled_at" field.
func CancelledAtLT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldCancelledAt, v))
}

// CancelledAtLTE applies the LTE predicate on the "cancelled_at" field.
func CancelledAtLTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldCancelledAt, v))
}

// CancelledAtIsNil applies the IsNil predicate on the "cancelled_at" field.
func CancelledAtIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldCancelledAt))
}

// CancelledAtNotNil applies the NotNil predicate on the "cancelled_at" field.
func CancelledAtNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldCancelledAt))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldErrorMessage, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Checkout) predicate.Checkout {
	return predicate.Checkout(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Checkout) predicate.Checkout {
	return predicate.Checkout(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Checkout) predicate.Checkout {
	return predicate.Checkout(sql.NotPredicates(p))
}
