# Benthos Flexprice - Staging Kafka Consumer
# Consumes from benthos-testing topic and sends to Flexprice

input:
  kafka:
    # Staging Kafka brokers
    addresses: 
      - ${FLEXPRICE_KAFKA_BROKERS}
    
    # Test topic
    topics:
      - benthos-testing
    
    # Consumer group (use a new group name to skip old messages)
    consumer_group: ${FLEXPRICE_KAFKA_CONSUMER_GROUP:benthos-flexprice-fresh}
    
    # Start from NEWEST to skip old broken messages
    start_from_oldest: false
    
    # SASL Authentication for Confluent Cloud
    tls:
      enabled: true
    
    sasl:
      mechanism: PLAIN
      user: ${FLEXPRICE_KAFKA_SASL_USER}
      password: ${FLEXPRICE_KAFKA_SASL_PASSWORD}
    
    # Client ID
    client_id: ${FLEXPRICE_KAFKA_CLIENT_ID:benthos-flexprice-collector}
    
    # Performance tuning
    commit_period: 1s
    max_processing_period: 100ms

pipeline:
  processors:
    # Transform Kafka message to Flexprice event format
    - mapping: |
        # Required fields
        root.event_name = this.event_name
        root.external_customer_id = this.external_customer_id.or(this.customer_id)
        
        # Properties - merge existing with metadata
        root.properties = this.properties.or({})
        
        # Source tracking
        root.source = "kafka-staging-benthos"
        
        # Timestamp handling
        root.timestamp = this.timestamp.or(now().format_timestamp("2006-01-02T15:04:05Z07:00"))
        
        # Optional fields
        root.event_id = this.event_id.or("")
        root.customer_id = this.customer_id.or("")
    
    # Log each event
    - log:
        level: INFO
        message: |
          [KAFKA→FLEXPRICE] Processing event:
          - Event Name: ${!json("event_name")}
          - Customer ID: ${!json("external_customer_id")}
          - Timestamp: ${!json("timestamp")}

output:
  flexprice:
    api_host: ${FLEXPRICE_API_HOST}
    api_key: ${FLEXPRICE_API_KEY}
    scheme: https

logger:
  level: INFO
  format: logfmt
  add_timestamp: true
