workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    swagger-json:
        inputs:
            - location: docs/swagger/swagger-3-0.json
        registry:
            location: registry.speakeasyapi.dev/flexprice/prod/swagger-json
    swagger-json-mcp:
        inputs:
            - location: docs/swagger/swagger-3-0-mcp.json
targets:
    flexprice-go:
        target: go
        source: swagger-json
        output: ./api/go
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/flexprice/prod/swagger-json-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
    flexprice-mcp:
        target: mcp-typescript
        source: swagger-json-mcp
        output: ./api/mcp
        publish:
            npm:
                token: $npm_token
    flexprice-python:
        target: python
        source: swagger-json
        output: ./api/python
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/flexprice/prod/swagger-json-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
    flexprice-typescript:
        target: typescript
        source: swagger-json
        output: ./api/typescript
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/flexprice/prod/swagger-json-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
