// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/checkout"
	"github.com/flexprice/flexprice/internal/types"
	"github.com/shopspring/decimal"
)

// CheckoutCreate is the builder for creating a Checkout entity.
type CheckoutCreate struct {
	config
	mutation *CheckoutMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (cc *CheckoutCreate) SetTenantID(s string) *CheckoutCreate {
	cc.mutation.SetTenantID(s)
	return cc
}

// SetStatus sets the "status" field.
func (cc *CheckoutCreate) SetStatus(s string) *CheckoutCreate {
	cc.mutation.SetStatus(s)
	return cc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableStatus(s *string) *CheckoutCreate {
	if s != nil {
		cc.SetStatus(*s)
	}
	return cc
}

// SetCreatedAt sets the "created_at" field.
func (cc *CheckoutCreate) SetCreatedAt(t time.Time) *CheckoutCreate {
	cc.mutation.SetCreatedAt(t)
	return cc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableCreatedAt(t *time.Time) *CheckoutCreate {
	if t != nil {
		cc.SetCreatedAt(*t)
	}
	return cc
}

// SetUpdatedAt sets the "updated_at" field.
func (cc *CheckoutCreate) SetUpdatedAt(t time.Time) *CheckoutCreate {
	cc.mutation.SetUpdatedAt(t)
	return cc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableUpdatedAt(t *time.Time) *CheckoutCreate {
	if t != nil {
		cc.SetUpdatedAt(*t)
	}
	return cc
}

// SetCreatedBy sets the "created_by" field.
func (cc *CheckoutCreate) SetCreatedBy(s string) *CheckoutCreate {
	cc.mutation.SetCreatedBy(s)
	return cc
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableCreatedBy(s *string) *CheckoutCreate {
	if s != nil {
		cc.SetCreatedBy(*s)
	}
	return cc
}

// SetUpdatedBy sets the "updated_by" field.
func (cc *CheckoutCreate) SetUpdatedBy(s string) *CheckoutCreate {
	cc.mutation.SetUpdatedBy(s)
	return cc
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableUpdatedBy(s *string) *CheckoutCreate {
	if s != nil {
		cc.SetUpdatedBy(*s)
	}
	return cc
}

// SetEnvironmentID sets the "environment_id" field.
func (cc *CheckoutCreate) SetEnvironmentID(s string) *CheckoutCreate {
	cc.mutation.SetEnvironmentID(s)
	return cc
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableEnvironmentID(s *string) *CheckoutCreate {
	if s != nil {
		cc.SetEnvironmentID(*s)
	}
	return cc
}

// SetCustomerID sets the "customer_id" field.
func (cc *CheckoutCreate) SetCustomerID(s string) *CheckoutCreate {
	cc.mutation.SetCustomerID(s)
	return cc
}

// SetEntityType sets the "entity_type" field.
func (cc *CheckoutCreate) SetEntityType(tet types.CheckoutEntityType) *CheckoutCreate {
	cc.mutation.SetEntityType(tet)
	return cc
}

// SetEntityID sets the "entity_id" field.
func (cc *CheckoutCreate) SetEntityID(s string) *CheckoutCreate {
	cc.mutation.SetEntityID(s)
	return cc
}

// SetCheckoutAction sets the "checkout_action" field.
func (cc *CheckoutCreate) SetCheckoutAction(ta types.CheckoutAction) *CheckoutCreate {
	cc.mutation.SetCheckoutAction(ta)
	return cc
}

// SetMode sets the "mode" field.
func (cc *CheckoutCreate) SetMode(to types.CheckoutObjective) *CheckoutCreate {
	cc.mutation.SetMode(to)
	return cc
}

// SetCheckoutStatus sets the "checkout_status" field.
func (cc *CheckoutCreate) SetCheckoutStatus(ts types.CheckoutStatus) *CheckoutCreate {
	cc.mutation.SetCheckoutStatus(ts)
	return cc
}

// SetNillableCheckoutStatus sets the "checkout_status" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableCheckoutStatus(ts *types.CheckoutStatus) *CheckoutCreate {
	if ts != nil {
		cc.SetCheckoutStatus(*ts)
	}
	return cc
}

// SetAmount sets the "amount" field.
func (cc *CheckoutCreate) SetAmount(d decimal.Decimal) *CheckoutCreate {
	cc.mutation.SetAmount(d)
	return cc
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableAmount(d *decimal.Decimal) *CheckoutCreate {
	if d != nil {
		cc.SetAmount(*d)
	}
	return cc
}

// SetCurrency sets the "currency" field.
func (cc *CheckoutCreate) SetCurrency(s string) *CheckoutCreate {
	cc.mutation.SetCurrency(s)
	return cc
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableCurrency(s *string) *CheckoutCreate {
	if s != nil {
		cc.SetCurrency(*s)
	}
	return cc
}

// SetProvider sets the "provider" field.
func (cc *CheckoutCreate) SetProvider(tp types.CheckoutProvider) *CheckoutCreate {
	cc.mutation.SetProvider(tp)
	return cc
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableProvider(tp *types.CheckoutProvider) *CheckoutCreate {
	if tp != nil {
		cc.SetProvider(*tp)
	}
	return cc
}

// SetProviderSessionID sets the "provider_session_id" field.
func (cc *CheckoutCreate) SetProviderSessionID(s string) *CheckoutCreate {
	cc.mutation.SetProviderSessionID(s)
	return cc
}

// SetNillableProviderSessionID sets the "provider_session_id" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableProviderSessionID(s *string) *CheckoutCreate {
	if s != nil {
		cc.SetProviderSessionID(*s)
	}
	return cc
}

// SetCheckoutURL sets the "checkout_url" field.
func (cc *CheckoutCreate) SetCheckoutURL(s string) *CheckoutCreate {
	cc.mutation.SetCheckoutURL(s)
	return cc
}

// SetNillableCheckoutURL sets the "checkout_url" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableCheckoutURL(s *string) *CheckoutCreate {
	if s != nil {
		cc.SetCheckoutURL(*s)
	}
	return cc
}

// SetSuccessURL sets the "success_url" field.
func (cc *CheckoutCreate) SetSuccessURL(s string) *CheckoutCreate {
	cc.mutation.SetSuccessURL(s)
	return cc
}

// SetNillableSuccessURL sets the "success_url" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableSuccessURL(s *string) *CheckoutCreate {
	if s != nil {
		cc.SetSuccessURL(*s)
	}
	return cc
}

// SetCancelURL sets the "cancel_url" field.
func (cc *CheckoutCreate) SetCancelURL(s string) *CheckoutCreate {
	cc.mutation.SetCancelURL(s)
	return cc
}

// SetNillableCancelURL sets the "cancel_url" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableCancelURL(s *string) *CheckoutCreate {
	if s != nil {
		cc.SetCancelURL(*s)
	}
	return cc
}

// SetConfiguration sets the "configuration" field.
func (cc *CheckoutCreate) SetConfiguration(m map[string]interface{}) *CheckoutCreate {
	cc.mutation.SetConfiguration(m)
	return cc
}

// SetExpiresAt sets the "expires_at" field.
func (cc *CheckoutCreate) SetExpiresAt(t time.Time) *CheckoutCreate {
	cc.mutation.SetExpiresAt(t)
	return cc
}

// SetCompletedAt sets the "completed_at" field.
func (cc *CheckoutCreate) SetCompletedAt(t time.Time) *CheckoutCreate {
	cc.mutation.SetCompletedAt(t)
	return cc
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableCompletedAt(t *time.Time) *CheckoutCreate {
	if t != nil {
		cc.SetCompletedAt(*t)
	}
	return cc
}

// SetCancelledAt sets the "cancelled_at" field.
func (cc *CheckoutCreate) SetCancelledAt(t time.Time) *CheckoutCreate {
	cc.mutation.SetCancelledAt(t)
	return cc
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableCancelledAt(t *time.Time) *CheckoutCreate {
	if t != nil {
		cc.SetCancelledAt(*t)
	}
	return cc
}

// SetFailureMessage sets the "failure_message" field.
func (cc *CheckoutCreate) SetFailureMessage(s string) *CheckoutCreate {
	cc.mutation.SetFailureMessage(s)
	return cc
}

// SetNillableFailureMessage sets the "failure_message" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableFailureMessage(s *string) *CheckoutCreate {
	if s != nil {
		cc.SetFailureMessage(*s)
	}
	return cc
}

// SetID sets the "id" field.
func (cc *CheckoutCreate) SetID(s string) *CheckoutCreate {
	cc.mutation.SetID(s)
	return cc
}

// Mutation returns the CheckoutMutation object of the builder.
func (cc *CheckoutCreate) Mutation() *CheckoutMutation {
	return cc.mutation
}

// Save creates the Checkout in the database.
func (cc *CheckoutCreate) Save(ctx context.Context) (*Checkout, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CheckoutCreate) SaveX(ctx context.Context) *Checkout {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CheckoutCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CheckoutCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *CheckoutCreate) defaults() {
	if _, ok := cc.mutation.Status(); !ok {
		v := checkout.DefaultStatus
		cc.mutation.SetStatus(v)
	}
	if _, ok := cc.mutation.CreatedAt(); !ok {
		v := checkout.DefaultCreatedAt()
		cc.mutation.SetCreatedAt(v)
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		v := checkout.DefaultUpdatedAt()
		cc.mutation.SetUpdatedAt(v)
	}
	if _, ok := cc.mutation.EnvironmentID(); !ok {
		v := checkout.DefaultEnvironmentID
		cc.mutation.SetEnvironmentID(v)
	}
	if _, ok := cc.mutation.CheckoutStatus(); !ok {
		v := checkout.DefaultCheckoutStatus
		cc.mutation.SetCheckoutStatus(v)
	}
	if _, ok := cc.mutation.Provider(); !ok {
		v := checkout.DefaultProvider
		cc.mutation.SetProvider(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CheckoutCreate) check() error {
	if _, ok := cc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Checkout.tenant_id"`)}
	}
	if v, ok := cc.mutation.TenantID(); ok {
		if err := checkout.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Checkout.tenant_id": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Checkout.status"`)}
	}
	if _, ok := cc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Checkout.created_at"`)}
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Checkout.updated_at"`)}
	}
	if _, ok := cc.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer_id", err: errors.New(`ent: missing required field "Checkout.customer_id"`)}
	}
	if v, ok := cc.mutation.CustomerID(); ok {
		if err := checkout.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`ent: validator failed for field "Checkout.customer_id": %w`, err)}
		}
	}
	if _, ok := cc.mutation.EntityType(); !ok {
		return &ValidationError{Name: "entity_type", err: errors.New(`ent: missing required field "Checkout.entity_type"`)}
	}
	if v, ok := cc.mutation.EntityType(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "Checkout.entity_type": %w`, err)}
		}
	}
	if _, ok := cc.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "Checkout.entity_id"`)}
	}
	if _, ok := cc.mutation.CheckoutAction(); !ok {
		return &ValidationError{Name: "checkout_action", err: errors.New(`ent: missing required field "Checkout.checkout_action"`)}
	}
	if v, ok := cc.mutation.CheckoutAction(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "checkout_action", err: fmt.Errorf(`ent: validator failed for field "Checkout.checkout_action": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "Checkout.mode"`)}
	}
	if v, ok := cc.mutation.Mode(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Checkout.mode": %w`, err)}
		}
	}
	if _, ok := cc.mutation.CheckoutStatus(); !ok {
		return &ValidationError{Name: "checkout_status", err: errors.New(`ent: missing required field "Checkout.checkout_status"`)}
	}
	if v, ok := cc.mutation.CheckoutStatus(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "checkout_status", err: fmt.Errorf(`ent: validator failed for field "Checkout.checkout_status": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "Checkout.provider"`)}
	}
	if v, ok := cc.mutation.Provider(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Checkout.provider": %w`, err)}
		}
	}
	if _, ok := cc.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "Checkout.expires_at"`)}
	}
	return nil
}

func (cc *CheckoutCreate) sqlSave(ctx context.Context) (*Checkout, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Checkout.ID type: %T", _spec.ID.Value)
		}
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CheckoutCreate) createSpec() (*Checkout, *sqlgraph.CreateSpec) {
	var (
		_node = &Checkout{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(checkout.Table, sqlgraph.NewFieldSpec(checkout.FieldID, field.TypeString))
	)
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cc.mutation.TenantID(); ok {
		_spec.SetField(checkout.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := cc.mutation.Status(); ok {
		_spec.SetField(checkout.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := cc.mutation.CreatedAt(); ok {
		_spec.SetField(checkout.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cc.mutation.UpdatedAt(); ok {
		_spec.SetField(checkout.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := cc.mutation.CreatedBy(); ok {
		_spec.SetField(checkout.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := cc.mutation.UpdatedBy(); ok {
		_spec.SetField(checkout.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := cc.mutation.EnvironmentID(); ok {
		_spec.SetField(checkout.FieldEnvironmentID, field.TypeString, value)
		_node.EnvironmentID = value
	}
	if value, ok := cc.mutation.CustomerID(); ok {
		_spec.SetField(checkout.FieldCustomerID, field.TypeString, value)
		_node.CustomerID = value
	}
	if value, ok := cc.mutation.EntityType(); ok {
		_spec.SetField(checkout.FieldEntityType, field.TypeString, value)
		_node.EntityType = value
	}
	if value, ok := cc.mutation.EntityID(); ok {
		_spec.SetField(checkout.FieldEntityID, field.TypeString, value)
		_node.EntityID = value
	}
	if value, ok := cc.mutation.CheckoutAction(); ok {
		_spec.SetField(checkout.FieldCheckoutAction, field.TypeString, value)
		_node.CheckoutAction = value
	}
	if value, ok := cc.mutation.Mode(); ok {
		_spec.SetField(checkout.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := cc.mutation.CheckoutStatus(); ok {
		_spec.SetField(checkout.FieldCheckoutStatus, field.TypeString, value)
		_node.CheckoutStatus = value
	}
	if value, ok := cc.mutation.Amount(); ok {
		_spec.SetField(checkout.FieldAmount, field.TypeOther, value)
		_node.Amount = &value
	}
	if value, ok := cc.mutation.Currency(); ok {
		_spec.SetField(checkout.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := cc.mutation.Provider(); ok {
		_spec.SetField(checkout.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := cc.mutation.ProviderSessionID(); ok {
		_spec.SetField(checkout.FieldProviderSessionID, field.TypeString, value)
		_node.ProviderSessionID = &value
	}
	if value, ok := cc.mutation.CheckoutURL(); ok {
		_spec.SetField(checkout.FieldCheckoutURL, field.TypeString, value)
		_node.CheckoutURL = &value
	}
	if value, ok := cc.mutation.SuccessURL(); ok {
		_spec.SetField(checkout.FieldSuccessURL, field.TypeString, value)
		_node.SuccessURL = &value
	}
	if value, ok := cc.mutation.CancelURL(); ok {
		_spec.SetField(checkout.FieldCancelURL, field.TypeString, value)
		_node.CancelURL = &value
	}
	if value, ok := cc.mutation.Configuration(); ok {
		_spec.SetField(checkout.FieldConfiguration, field.TypeJSON, value)
		_node.Configuration = value
	}
	if value, ok := cc.mutation.ExpiresAt(); ok {
		_spec.SetField(checkout.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := cc.mutation.CompletedAt(); ok {
		_spec.SetField(checkout.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := cc.mutation.CancelledAt(); ok {
		_spec.SetField(checkout.FieldCancelledAt, field.TypeTime, value)
		_node.CancelledAt = &value
	}
	if value, ok := cc.mutation.FailureMessage(); ok {
		_spec.SetField(checkout.FieldFailureMessage, field.TypeString, value)
		_node.FailureMessage = &value
	}
	return _node, _spec
}

// CheckoutCreateBulk is the builder for creating many Checkout entities in bulk.
type CheckoutCreateBulk struct {
	config
	err      error
	builders []*CheckoutCreate
}

// Save creates the Checkout entities in the database.
func (ccb *CheckoutCreateBulk) Save(ctx context.Context) ([]*Checkout, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Checkout, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CheckoutMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CheckoutCreateBulk) SaveX(ctx context.Context) []*Checkout {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CheckoutCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CheckoutCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
