// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/checkout"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/internal/types"
	"github.com/shopspring/decimal"
)

// CheckoutUpdate is the builder for updating Checkout entities.
type CheckoutUpdate struct {
	config
	hooks    []Hook
	mutation *CheckoutMutation
}

// Where appends a list predicates to the CheckoutUpdate builder.
func (cu *CheckoutUpdate) Where(ps ...predicate.Checkout) *CheckoutUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetStatus sets the "status" field.
func (cu *CheckoutUpdate) SetStatus(s string) *CheckoutUpdate {
	cu.mutation.SetStatus(s)
	return cu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableStatus(s *string) *CheckoutUpdate {
	if s != nil {
		cu.SetStatus(*s)
	}
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *CheckoutUpdate) SetUpdatedAt(t time.Time) *CheckoutUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetUpdatedBy sets the "updated_by" field.
func (cu *CheckoutUpdate) SetUpdatedBy(s string) *CheckoutUpdate {
	cu.mutation.SetUpdatedBy(s)
	return cu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableUpdatedBy(s *string) *CheckoutUpdate {
	if s != nil {
		cu.SetUpdatedBy(*s)
	}
	return cu
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (cu *CheckoutUpdate) ClearUpdatedBy() *CheckoutUpdate {
	cu.mutation.ClearUpdatedBy()
	return cu
}

// SetCustomerID sets the "customer_id" field.
func (cu *CheckoutUpdate) SetCustomerID(s string) *CheckoutUpdate {
	cu.mutation.SetCustomerID(s)
	return cu
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableCustomerID(s *string) *CheckoutUpdate {
	if s != nil {
		cu.SetCustomerID(*s)
	}
	return cu
}

// SetEntityType sets the "entity_type" field.
func (cu *CheckoutUpdate) SetEntityType(tet types.CheckoutEntityType) *CheckoutUpdate {
	cu.mutation.SetEntityType(tet)
	return cu
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableEntityType(tet *types.CheckoutEntityType) *CheckoutUpdate {
	if tet != nil {
		cu.SetEntityType(*tet)
	}
	return cu
}

// SetEntityID sets the "entity_id" field.
func (cu *CheckoutUpdate) SetEntityID(s string) *CheckoutUpdate {
	cu.mutation.SetEntityID(s)
	return cu
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableEntityID(s *string) *CheckoutUpdate {
	if s != nil {
		cu.SetEntityID(*s)
	}
	return cu
}

// SetCheckoutAction sets the "checkout_action" field.
func (cu *CheckoutUpdate) SetCheckoutAction(ta types.CheckoutAction) *CheckoutUpdate {
	cu.mutation.SetCheckoutAction(ta)
	return cu
}

// SetNillableCheckoutAction sets the "checkout_action" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableCheckoutAction(ta *types.CheckoutAction) *CheckoutUpdate {
	if ta != nil {
		cu.SetCheckoutAction(*ta)
	}
	return cu
}

// SetMode sets the "mode" field.
func (cu *CheckoutUpdate) SetMode(to types.CheckoutMode) *CheckoutUpdate {
	cu.mutation.SetMode(to)
	return cu
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableMode(to *types.CheckoutMode) *CheckoutUpdate {
	if to != nil {
		cu.SetMode(*to)
	}
	return cu
}

// SetCheckoutStatus sets the "checkout_status" field.
func (cu *CheckoutUpdate) SetCheckoutStatus(ts types.CheckoutStatus) *CheckoutUpdate {
	cu.mutation.SetCheckoutStatus(ts)
	return cu
}

// SetNillableCheckoutStatus sets the "checkout_status" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableCheckoutStatus(ts *types.CheckoutStatus) *CheckoutUpdate {
	if ts != nil {
		cu.SetCheckoutStatus(*ts)
	}
	return cu
}

// SetAmount sets the "amount" field.
func (cu *CheckoutUpdate) SetAmount(d decimal.Decimal) *CheckoutUpdate {
	cu.mutation.SetAmount(d)
	return cu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableAmount(d *decimal.Decimal) *CheckoutUpdate {
	if d != nil {
		cu.SetAmount(*d)
	}
	return cu
}

// ClearAmount clears the value of the "amount" field.
func (cu *CheckoutUpdate) ClearAmount() *CheckoutUpdate {
	cu.mutation.ClearAmount()
	return cu
}

// SetCurrency sets the "currency" field.
func (cu *CheckoutUpdate) SetCurrency(s string) *CheckoutUpdate {
	cu.mutation.SetCurrency(s)
	return cu
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableCurrency(s *string) *CheckoutUpdate {
	if s != nil {
		cu.SetCurrency(*s)
	}
	return cu
}

// ClearCurrency clears the value of the "currency" field.
func (cu *CheckoutUpdate) ClearCurrency() *CheckoutUpdate {
	cu.mutation.ClearCurrency()
	return cu
}

// SetProvider sets the "provider" field.
func (cu *CheckoutUpdate) SetProvider(tp types.CheckoutProvider) *CheckoutUpdate {
	cu.mutation.SetProvider(tp)
	return cu
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableProvider(tp *types.CheckoutProvider) *CheckoutUpdate {
	if tp != nil {
		cu.SetProvider(*tp)
	}
	return cu
}

// SetProviderSessionID sets the "provider_session_id" field.
func (cu *CheckoutUpdate) SetProviderSessionID(s string) *CheckoutUpdate {
	cu.mutation.SetProviderSessionID(s)
	return cu
}

// SetNillableProviderSessionID sets the "provider_session_id" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableProviderSessionID(s *string) *CheckoutUpdate {
	if s != nil {
		cu.SetProviderSessionID(*s)
	}
	return cu
}

// ClearProviderSessionID clears the value of the "provider_session_id" field.
func (cu *CheckoutUpdate) ClearProviderSessionID() *CheckoutUpdate {
	cu.mutation.ClearProviderSessionID()
	return cu
}

// SetCheckoutURL sets the "checkout_url" field.
func (cu *CheckoutUpdate) SetCheckoutURL(s string) *CheckoutUpdate {
	cu.mutation.SetCheckoutURL(s)
	return cu
}

// SetNillableCheckoutURL sets the "checkout_url" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableCheckoutURL(s *string) *CheckoutUpdate {
	if s != nil {
		cu.SetCheckoutURL(*s)
	}
	return cu
}

// ClearCheckoutURL clears the value of the "checkout_url" field.
func (cu *CheckoutUpdate) ClearCheckoutURL() *CheckoutUpdate {
	cu.mutation.ClearCheckoutURL()
	return cu
}

// SetSuccessURL sets the "success_url" field.
func (cu *CheckoutUpdate) SetSuccessURL(s string) *CheckoutUpdate {
	cu.mutation.SetSuccessURL(s)
	return cu
}

// SetNillableSuccessURL sets the "success_url" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableSuccessURL(s *string) *CheckoutUpdate {
	if s != nil {
		cu.SetSuccessURL(*s)
	}
	return cu
}

// ClearSuccessURL clears the value of the "success_url" field.
func (cu *CheckoutUpdate) ClearSuccessURL() *CheckoutUpdate {
	cu.mutation.ClearSuccessURL()
	return cu
}

// SetCancelURL sets the "cancel_url" field.
func (cu *CheckoutUpdate) SetCancelURL(s string) *CheckoutUpdate {
	cu.mutation.SetCancelURL(s)
	return cu
}

// SetNillableCancelURL sets the "cancel_url" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableCancelURL(s *string) *CheckoutUpdate {
	if s != nil {
		cu.SetCancelURL(*s)
	}
	return cu
}

// ClearCancelURL clears the value of the "cancel_url" field.
func (cu *CheckoutUpdate) ClearCancelURL() *CheckoutUpdate {
	cu.mutation.ClearCancelURL()
	return cu
}

// SetConfiguration sets the "configuration" field.
func (cu *CheckoutUpdate) SetConfiguration(m map[string]interface{}) *CheckoutUpdate {
	cu.mutation.SetConfiguration(m)
	return cu
}

// ClearConfiguration clears the value of the "configuration" field.
func (cu *CheckoutUpdate) ClearConfiguration() *CheckoutUpdate {
	cu.mutation.ClearConfiguration()
	return cu
}

// SetExpiresAt sets the "expires_at" field.
func (cu *CheckoutUpdate) SetExpiresAt(t time.Time) *CheckoutUpdate {
	cu.mutation.SetExpiresAt(t)
	return cu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableExpiresAt(t *time.Time) *CheckoutUpdate {
	if t != nil {
		cu.SetExpiresAt(*t)
	}
	return cu
}

// SetCompletedAt sets the "completed_at" field.
func (cu *CheckoutUpdate) SetCompletedAt(t time.Time) *CheckoutUpdate {
	cu.mutation.SetCompletedAt(t)
	return cu
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableCompletedAt(t *time.Time) *CheckoutUpdate {
	if t != nil {
		cu.SetCompletedAt(*t)
	}
	return cu
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (cu *CheckoutUpdate) ClearCompletedAt() *CheckoutUpdate {
	cu.mutation.ClearCompletedAt()
	return cu
}

// SetCancelledAt sets the "cancelled_at" field.
func (cu *CheckoutUpdate) SetCancelledAt(t time.Time) *CheckoutUpdate {
	cu.mutation.SetCancelledAt(t)
	return cu
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableCancelledAt(t *time.Time) *CheckoutUpdate {
	if t != nil {
		cu.SetCancelledAt(*t)
	}
	return cu
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (cu *CheckoutUpdate) ClearCancelledAt() *CheckoutUpdate {
	cu.mutation.ClearCancelledAt()
	return cu
}

// SetFailureMessage sets the "failure_message" field.
func (cu *CheckoutUpdate) SetFailureMessage(s string) *CheckoutUpdate {
	cu.mutation.SetFailureMessage(s)
	return cu
}

// SetNillableFailureMessage sets the "failure_message" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableFailureMessage(s *string) *CheckoutUpdate {
	if s != nil {
		cu.SetFailureMessage(*s)
	}
	return cu
}

// ClearFailureMessage clears the value of the "failure_message" field.
func (cu *CheckoutUpdate) ClearFailureMessage() *CheckoutUpdate {
	cu.mutation.ClearFailureMessage()
	return cu
}

// Mutation returns the CheckoutMutation object of the builder.
func (cu *CheckoutUpdate) Mutation() *CheckoutMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CheckoutUpdate) Save(ctx context.Context) (int, error) {
	cu.defaults()
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CheckoutUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CheckoutUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CheckoutUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *CheckoutUpdate) defaults() {
	if _, ok := cu.mutation.UpdatedAt(); !ok {
		v := checkout.UpdateDefaultUpdatedAt()
		cu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CheckoutUpdate) check() error {
	if v, ok := cu.mutation.CustomerID(); ok {
		if err := checkout.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`ent: validator failed for field "Checkout.customer_id": %w`, err)}
		}
	}
	if v, ok := cu.mutation.EntityType(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "Checkout.entity_type": %w`, err)}
		}
	}
	if v, ok := cu.mutation.CheckoutAction(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "checkout_action", err: fmt.Errorf(`ent: validator failed for field "Checkout.checkout_action": %w`, err)}
		}
	}
	if v, ok := cu.mutation.Mode(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Checkout.mode": %w`, err)}
		}
	}
	if v, ok := cu.mutation.CheckoutStatus(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "checkout_status", err: fmt.Errorf(`ent: validator failed for field "Checkout.checkout_status": %w`, err)}
		}
	}
	if v, ok := cu.mutation.Provider(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Checkout.provider": %w`, err)}
		}
	}
	return nil
}

func (cu *CheckoutUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkout.Table, checkout.Columns, sqlgraph.NewFieldSpec(checkout.FieldID, field.TypeString))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Status(); ok {
		_spec.SetField(checkout.FieldStatus, field.TypeString, value)
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(checkout.FieldUpdatedAt, field.TypeTime, value)
	}
	if cu.mutation.CreatedByCleared() {
		_spec.ClearField(checkout.FieldCreatedBy, field.TypeString)
	}
	if value, ok := cu.mutation.UpdatedBy(); ok {
		_spec.SetField(checkout.FieldUpdatedBy, field.TypeString, value)
	}
	if cu.mutation.UpdatedByCleared() {
		_spec.ClearField(checkout.FieldUpdatedBy, field.TypeString)
	}
	if cu.mutation.EnvironmentIDCleared() {
		_spec.ClearField(checkout.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := cu.mutation.CustomerID(); ok {
		_spec.SetField(checkout.FieldCustomerID, field.TypeString, value)
	}
	if value, ok := cu.mutation.EntityType(); ok {
		_spec.SetField(checkout.FieldEntityType, field.TypeString, value)
	}
	if value, ok := cu.mutation.EntityID(); ok {
		_spec.SetField(checkout.FieldEntityID, field.TypeString, value)
	}
	if value, ok := cu.mutation.CheckoutAction(); ok {
		_spec.SetField(checkout.FieldCheckoutAction, field.TypeString, value)
	}
	if value, ok := cu.mutation.Mode(); ok {
		_spec.SetField(checkout.FieldMode, field.TypeString, value)
	}
	if value, ok := cu.mutation.CheckoutStatus(); ok {
		_spec.SetField(checkout.FieldCheckoutStatus, field.TypeString, value)
	}
	if value, ok := cu.mutation.Amount(); ok {
		_spec.SetField(checkout.FieldAmount, field.TypeOther, value)
	}
	if cu.mutation.AmountCleared() {
		_spec.ClearField(checkout.FieldAmount, field.TypeOther)
	}
	if value, ok := cu.mutation.Currency(); ok {
		_spec.SetField(checkout.FieldCurrency, field.TypeString, value)
	}
	if cu.mutation.CurrencyCleared() {
		_spec.ClearField(checkout.FieldCurrency, field.TypeString)
	}
	if value, ok := cu.mutation.Provider(); ok {
		_spec.SetField(checkout.FieldProvider, field.TypeString, value)
	}
	if value, ok := cu.mutation.ProviderSessionID(); ok {
		_spec.SetField(checkout.FieldProviderSessionID, field.TypeString, value)
	}
	if cu.mutation.ProviderSessionIDCleared() {
		_spec.ClearField(checkout.FieldProviderSessionID, field.TypeString)
	}
	if value, ok := cu.mutation.CheckoutURL(); ok {
		_spec.SetField(checkout.FieldCheckoutURL, field.TypeString, value)
	}
	if cu.mutation.CheckoutURLCleared() {
		_spec.ClearField(checkout.FieldCheckoutURL, field.TypeString)
	}
	if value, ok := cu.mutation.SuccessURL(); ok {
		_spec.SetField(checkout.FieldSuccessURL, field.TypeString, value)
	}
	if cu.mutation.SuccessURLCleared() {
		_spec.ClearField(checkout.FieldSuccessURL, field.TypeString)
	}
	if value, ok := cu.mutation.CancelURL(); ok {
		_spec.SetField(checkout.FieldCancelURL, field.TypeString, value)
	}
	if cu.mutation.CancelURLCleared() {
		_spec.ClearField(checkout.FieldCancelURL, field.TypeString)
	}
	if value, ok := cu.mutation.Configuration(); ok {
		_spec.SetField(checkout.FieldConfiguration, field.TypeJSON, value)
	}
	if cu.mutation.ConfigurationCleared() {
		_spec.ClearField(checkout.FieldConfiguration, field.TypeJSON)
	}
	if value, ok := cu.mutation.ExpiresAt(); ok {
		_spec.SetField(checkout.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := cu.mutation.CompletedAt(); ok {
		_spec.SetField(checkout.FieldCompletedAt, field.TypeTime, value)
	}
	if cu.mutation.CompletedAtCleared() {
		_spec.ClearField(checkout.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := cu.mutation.CancelledAt(); ok {
		_spec.SetField(checkout.FieldCancelledAt, field.TypeTime, value)
	}
	if cu.mutation.CancelledAtCleared() {
		_spec.ClearField(checkout.FieldCancelledAt, field.TypeTime)
	}
	if value, ok := cu.mutation.FailureMessage(); ok {
		_spec.SetField(checkout.FieldFailureMessage, field.TypeString, value)
	}
	if cu.mutation.FailureMessageCleared() {
		_spec.ClearField(checkout.FieldFailureMessage, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkout.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CheckoutUpdateOne is the builder for updating a single Checkout entity.
type CheckoutUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CheckoutMutation
}

// SetStatus sets the "status" field.
func (cuo *CheckoutUpdateOne) SetStatus(s string) *CheckoutUpdateOne {
	cuo.mutation.SetStatus(s)
	return cuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableStatus(s *string) *CheckoutUpdateOne {
	if s != nil {
		cuo.SetStatus(*s)
	}
	return cuo
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *CheckoutUpdateOne) SetUpdatedAt(t time.Time) *CheckoutUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetUpdatedBy sets the "updated_by" field.
func (cuo *CheckoutUpdateOne) SetUpdatedBy(s string) *CheckoutUpdateOne {
	cuo.mutation.SetUpdatedBy(s)
	return cuo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableUpdatedBy(s *string) *CheckoutUpdateOne {
	if s != nil {
		cuo.SetUpdatedBy(*s)
	}
	return cuo
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (cuo *CheckoutUpdateOne) ClearUpdatedBy() *CheckoutUpdateOne {
	cuo.mutation.ClearUpdatedBy()
	return cuo
}

// SetCustomerID sets the "customer_id" field.
func (cuo *CheckoutUpdateOne) SetCustomerID(s string) *CheckoutUpdateOne {
	cuo.mutation.SetCustomerID(s)
	return cuo
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableCustomerID(s *string) *CheckoutUpdateOne {
	if s != nil {
		cuo.SetCustomerID(*s)
	}
	return cuo
}

// SetEntityType sets the "entity_type" field.
func (cuo *CheckoutUpdateOne) SetEntityType(tet types.CheckoutEntityType) *CheckoutUpdateOne {
	cuo.mutation.SetEntityType(tet)
	return cuo
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableEntityType(tet *types.CheckoutEntityType) *CheckoutUpdateOne {
	if tet != nil {
		cuo.SetEntityType(*tet)
	}
	return cuo
}

// SetEntityID sets the "entity_id" field.
func (cuo *CheckoutUpdateOne) SetEntityID(s string) *CheckoutUpdateOne {
	cuo.mutation.SetEntityID(s)
	return cuo
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableEntityID(s *string) *CheckoutUpdateOne {
	if s != nil {
		cuo.SetEntityID(*s)
	}
	return cuo
}

// SetCheckoutAction sets the "checkout_action" field.
func (cuo *CheckoutUpdateOne) SetCheckoutAction(ta types.CheckoutAction) *CheckoutUpdateOne {
	cuo.mutation.SetCheckoutAction(ta)
	return cuo
}

// SetNillableCheckoutAction sets the "checkout_action" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableCheckoutAction(ta *types.CheckoutAction) *CheckoutUpdateOne {
	if ta != nil {
		cuo.SetCheckoutAction(*ta)
	}
	return cuo
}

// SetMode sets the "mode" field.
func (cuo *CheckoutUpdateOne) SetMode(to types.CheckoutMode) *CheckoutUpdateOne {
	cuo.mutation.SetMode(to)
	return cuo
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableMode(to *types.CheckoutMode) *CheckoutUpdateOne {
	if to != nil {
		cuo.SetMode(*to)
	}
	return cuo
}

// SetCheckoutStatus sets the "checkout_status" field.
func (cuo *CheckoutUpdateOne) SetCheckoutStatus(ts types.CheckoutStatus) *CheckoutUpdateOne {
	cuo.mutation.SetCheckoutStatus(ts)
	return cuo
}

// SetNillableCheckoutStatus sets the "checkout_status" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableCheckoutStatus(ts *types.CheckoutStatus) *CheckoutUpdateOne {
	if ts != nil {
		cuo.SetCheckoutStatus(*ts)
	}
	return cuo
}

// SetAmount sets the "amount" field.
func (cuo *CheckoutUpdateOne) SetAmount(d decimal.Decimal) *CheckoutUpdateOne {
	cuo.mutation.SetAmount(d)
	return cuo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableAmount(d *decimal.Decimal) *CheckoutUpdateOne {
	if d != nil {
		cuo.SetAmount(*d)
	}
	return cuo
}

// ClearAmount clears the value of the "amount" field.
func (cuo *CheckoutUpdateOne) ClearAmount() *CheckoutUpdateOne {
	cuo.mutation.ClearAmount()
	return cuo
}

// SetCurrency sets the "currency" field.
func (cuo *CheckoutUpdateOne) SetCurrency(s string) *CheckoutUpdateOne {
	cuo.mutation.SetCurrency(s)
	return cuo
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableCurrency(s *string) *CheckoutUpdateOne {
	if s != nil {
		cuo.SetCurrency(*s)
	}
	return cuo
}

// ClearCurrency clears the value of the "currency" field.
func (cuo *CheckoutUpdateOne) ClearCurrency() *CheckoutUpdateOne {
	cuo.mutation.ClearCurrency()
	return cuo
}

// SetProvider sets the "provider" field.
func (cuo *CheckoutUpdateOne) SetProvider(tp types.CheckoutProvider) *CheckoutUpdateOne {
	cuo.mutation.SetProvider(tp)
	return cuo
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableProvider(tp *types.CheckoutProvider) *CheckoutUpdateOne {
	if tp != nil {
		cuo.SetProvider(*tp)
	}
	return cuo
}

// SetProviderSessionID sets the "provider_session_id" field.
func (cuo *CheckoutUpdateOne) SetProviderSessionID(s string) *CheckoutUpdateOne {
	cuo.mutation.SetProviderSessionID(s)
	return cuo
}

// SetNillableProviderSessionID sets the "provider_session_id" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableProviderSessionID(s *string) *CheckoutUpdateOne {
	if s != nil {
		cuo.SetProviderSessionID(*s)
	}
	return cuo
}

// ClearProviderSessionID clears the value of the "provider_session_id" field.
func (cuo *CheckoutUpdateOne) ClearProviderSessionID() *CheckoutUpdateOne {
	cuo.mutation.ClearProviderSessionID()
	return cuo
}

// SetCheckoutURL sets the "checkout_url" field.
func (cuo *CheckoutUpdateOne) SetCheckoutURL(s string) *CheckoutUpdateOne {
	cuo.mutation.SetCheckoutURL(s)
	return cuo
}

// SetNillableCheckoutURL sets the "checkout_url" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableCheckoutURL(s *string) *CheckoutUpdateOne {
	if s != nil {
		cuo.SetCheckoutURL(*s)
	}
	return cuo
}

// ClearCheckoutURL clears the value of the "checkout_url" field.
func (cuo *CheckoutUpdateOne) ClearCheckoutURL() *CheckoutUpdateOne {
	cuo.mutation.ClearCheckoutURL()
	return cuo
}

// SetSuccessURL sets the "success_url" field.
func (cuo *CheckoutUpdateOne) SetSuccessURL(s string) *CheckoutUpdateOne {
	cuo.mutation.SetSuccessURL(s)
	return cuo
}

// SetNillableSuccessURL sets the "success_url" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableSuccessURL(s *string) *CheckoutUpdateOne {
	if s != nil {
		cuo.SetSuccessURL(*s)
	}
	return cuo
}

// ClearSuccessURL clears the value of the "success_url" field.
func (cuo *CheckoutUpdateOne) ClearSuccessURL() *CheckoutUpdateOne {
	cuo.mutation.ClearSuccessURL()
	return cuo
}

// SetCancelURL sets the "cancel_url" field.
func (cuo *CheckoutUpdateOne) SetCancelURL(s string) *CheckoutUpdateOne {
	cuo.mutation.SetCancelURL(s)
	return cuo
}

// SetNillableCancelURL sets the "cancel_url" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableCancelURL(s *string) *CheckoutUpdateOne {
	if s != nil {
		cuo.SetCancelURL(*s)
	}
	return cuo
}

// ClearCancelURL clears the value of the "cancel_url" field.
func (cuo *CheckoutUpdateOne) ClearCancelURL() *CheckoutUpdateOne {
	cuo.mutation.ClearCancelURL()
	return cuo
}

// SetConfiguration sets the "configuration" field.
func (cuo *CheckoutUpdateOne) SetConfiguration(m map[string]interface{}) *CheckoutUpdateOne {
	cuo.mutation.SetConfiguration(m)
	return cuo
}

// ClearConfiguration clears the value of the "configuration" field.
func (cuo *CheckoutUpdateOne) ClearConfiguration() *CheckoutUpdateOne {
	cuo.mutation.ClearConfiguration()
	return cuo
}

// SetExpiresAt sets the "expires_at" field.
func (cuo *CheckoutUpdateOne) SetExpiresAt(t time.Time) *CheckoutUpdateOne {
	cuo.mutation.SetExpiresAt(t)
	return cuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableExpiresAt(t *time.Time) *CheckoutUpdateOne {
	if t != nil {
		cuo.SetExpiresAt(*t)
	}
	return cuo
}

// SetCompletedAt sets the "completed_at" field.
func (cuo *CheckoutUpdateOne) SetCompletedAt(t time.Time) *CheckoutUpdateOne {
	cuo.mutation.SetCompletedAt(t)
	return cuo
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableCompletedAt(t *time.Time) *CheckoutUpdateOne {
	if t != nil {
		cuo.SetCompletedAt(*t)
	}
	return cuo
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (cuo *CheckoutUpdateOne) ClearCompletedAt() *CheckoutUpdateOne {
	cuo.mutation.ClearCompletedAt()
	return cuo
}

// SetCancelledAt sets the "cancelled_at" field.
func (cuo *CheckoutUpdateOne) SetCancelledAt(t time.Time) *CheckoutUpdateOne {
	cuo.mutation.SetCancelledAt(t)
	return cuo
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableCancelledAt(t *time.Time) *CheckoutUpdateOne {
	if t != nil {
		cuo.SetCancelledAt(*t)
	}
	return cuo
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (cuo *CheckoutUpdateOne) ClearCancelledAt() *CheckoutUpdateOne {
	cuo.mutation.ClearCancelledAt()
	return cuo
}

// SetFailureMessage sets the "failure_message" field.
func (cuo *CheckoutUpdateOne) SetFailureMessage(s string) *CheckoutUpdateOne {
	cuo.mutation.SetFailureMessage(s)
	return cuo
}

// SetNillableFailureMessage sets the "failure_message" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableFailureMessage(s *string) *CheckoutUpdateOne {
	if s != nil {
		cuo.SetFailureMessage(*s)
	}
	return cuo
}

// ClearFailureMessage clears the value of the "failure_message" field.
func (cuo *CheckoutUpdateOne) ClearFailureMessage() *CheckoutUpdateOne {
	cuo.mutation.ClearFailureMessage()
	return cuo
}

// Mutation returns the CheckoutMutation object of the builder.
func (cuo *CheckoutUpdateOne) Mutation() *CheckoutMutation {
	return cuo.mutation
}

// Where appends a list predicates to the CheckoutUpdate builder.
func (cuo *CheckoutUpdateOne) Where(ps ...predicate.Checkout) *CheckoutUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CheckoutUpdateOne) Select(field string, fields ...string) *CheckoutUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Checkout entity.
func (cuo *CheckoutUpdateOne) Save(ctx context.Context) (*Checkout, error) {
	cuo.defaults()
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CheckoutUpdateOne) SaveX(ctx context.Context) *Checkout {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CheckoutUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CheckoutUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *CheckoutUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdatedAt(); !ok {
		v := checkout.UpdateDefaultUpdatedAt()
		cuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CheckoutUpdateOne) check() error {
	if v, ok := cuo.mutation.CustomerID(); ok {
		if err := checkout.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`ent: validator failed for field "Checkout.customer_id": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.EntityType(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "Checkout.entity_type": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.CheckoutAction(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "checkout_action", err: fmt.Errorf(`ent: validator failed for field "Checkout.checkout_action": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.Mode(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Checkout.mode": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.CheckoutStatus(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "checkout_status", err: fmt.Errorf(`ent: validator failed for field "Checkout.checkout_status": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.Provider(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Checkout.provider": %w`, err)}
		}
	}
	return nil
}

func (cuo *CheckoutUpdateOne) sqlSave(ctx context.Context) (_node *Checkout, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkout.Table, checkout.Columns, sqlgraph.NewFieldSpec(checkout.FieldID, field.TypeString))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Checkout.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkout.FieldID)
		for _, f := range fields {
			if !checkout.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checkout.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Status(); ok {
		_spec.SetField(checkout.FieldStatus, field.TypeString, value)
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(checkout.FieldUpdatedAt, field.TypeTime, value)
	}
	if cuo.mutation.CreatedByCleared() {
		_spec.ClearField(checkout.FieldCreatedBy, field.TypeString)
	}
	if value, ok := cuo.mutation.UpdatedBy(); ok {
		_spec.SetField(checkout.FieldUpdatedBy, field.TypeString, value)
	}
	if cuo.mutation.UpdatedByCleared() {
		_spec.ClearField(checkout.FieldUpdatedBy, field.TypeString)
	}
	if cuo.mutation.EnvironmentIDCleared() {
		_spec.ClearField(checkout.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := cuo.mutation.CustomerID(); ok {
		_spec.SetField(checkout.FieldCustomerID, field.TypeString, value)
	}
	if value, ok := cuo.mutation.EntityType(); ok {
		_spec.SetField(checkout.FieldEntityType, field.TypeString, value)
	}
	if value, ok := cuo.mutation.EntityID(); ok {
		_spec.SetField(checkout.FieldEntityID, field.TypeString, value)
	}
	if value, ok := cuo.mutation.CheckoutAction(); ok {
		_spec.SetField(checkout.FieldCheckoutAction, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Mode(); ok {
		_spec.SetField(checkout.FieldMode, field.TypeString, value)
	}
	if value, ok := cuo.mutation.CheckoutStatus(); ok {
		_spec.SetField(checkout.FieldCheckoutStatus, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Amount(); ok {
		_spec.SetField(checkout.FieldAmount, field.TypeOther, value)
	}
	if cuo.mutation.AmountCleared() {
		_spec.ClearField(checkout.FieldAmount, field.TypeOther)
	}
	if value, ok := cuo.mutation.Currency(); ok {
		_spec.SetField(checkout.FieldCurrency, field.TypeString, value)
	}
	if cuo.mutation.CurrencyCleared() {
		_spec.ClearField(checkout.FieldCurrency, field.TypeString)
	}
	if value, ok := cuo.mutation.Provider(); ok {
		_spec.SetField(checkout.FieldProvider, field.TypeString, value)
	}
	if value, ok := cuo.mutation.ProviderSessionID(); ok {
		_spec.SetField(checkout.FieldProviderSessionID, field.TypeString, value)
	}
	if cuo.mutation.ProviderSessionIDCleared() {
		_spec.ClearField(checkout.FieldProviderSessionID, field.TypeString)
	}
	if value, ok := cuo.mutation.CheckoutURL(); ok {
		_spec.SetField(checkout.FieldCheckoutURL, field.TypeString, value)
	}
	if cuo.mutation.CheckoutURLCleared() {
		_spec.ClearField(checkout.FieldCheckoutURL, field.TypeString)
	}
	if value, ok := cuo.mutation.SuccessURL(); ok {
		_spec.SetField(checkout.FieldSuccessURL, field.TypeString, value)
	}
	if cuo.mutation.SuccessURLCleared() {
		_spec.ClearField(checkout.FieldSuccessURL, field.TypeString)
	}
	if value, ok := cuo.mutation.CancelURL(); ok {
		_spec.SetField(checkout.FieldCancelURL, field.TypeString, value)
	}
	if cuo.mutation.CancelURLCleared() {
		_spec.ClearField(checkout.FieldCancelURL, field.TypeString)
	}
	if value, ok := cuo.mutation.Configuration(); ok {
		_spec.SetField(checkout.FieldConfiguration, field.TypeJSON, value)
	}
	if cuo.mutation.ConfigurationCleared() {
		_spec.ClearField(checkout.FieldConfiguration, field.TypeJSON)
	}
	if value, ok := cuo.mutation.ExpiresAt(); ok {
		_spec.SetField(checkout.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.CompletedAt(); ok {
		_spec.SetField(checkout.FieldCompletedAt, field.TypeTime, value)
	}
	if cuo.mutation.CompletedAtCleared() {
		_spec.ClearField(checkout.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := cuo.mutation.CancelledAt(); ok {
		_spec.SetField(checkout.FieldCancelledAt, field.TypeTime, value)
	}
	if cuo.mutation.CancelledAtCleared() {
		_spec.ClearField(checkout.FieldCancelledAt, field.TypeTime)
	}
	if value, ok := cuo.mutation.FailureMessage(); ok {
		_spec.SetField(checkout.FieldFailureMessage, field.TypeString, value)
	}
	if cuo.mutation.FailureMessageCleared() {
		_spec.ClearField(checkout.FieldFailureMessage, field.TypeString)
	}
	_node = &Checkout{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkout.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
