// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/incomingwebhookevent"
	"github.com/flexprice/flexprice/ent/predicate"
)

// IncomingWebhookEventQuery is the builder for querying IncomingWebhookEvent entities.
type IncomingWebhookEventQuery struct {
	config
	ctx        *QueryContext
	order      []incomingwebhookevent.OrderOption
	inters     []Interceptor
	predicates []predicate.IncomingWebhookEvent
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IncomingWebhookEventQuery builder.
func (iweq *IncomingWebhookEventQuery) Where(ps ...predicate.IncomingWebhookEvent) *IncomingWebhookEventQuery {
	iweq.predicates = append(iweq.predicates, ps...)
	return iweq
}

// Limit the number of records to be returned by this query.
func (iweq *IncomingWebhookEventQuery) Limit(limit int) *IncomingWebhookEventQuery {
	iweq.ctx.Limit = &limit
	return iweq
}

// Offset to start from.
func (iweq *IncomingWebhookEventQuery) Offset(offset int) *IncomingWebhookEventQuery {
	iweq.ctx.Offset = &offset
	return iweq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (iweq *IncomingWebhookEventQuery) Unique(unique bool) *IncomingWebhookEventQuery {
	iweq.ctx.Unique = &unique
	return iweq
}

// Order specifies how the records should be ordered.
func (iweq *IncomingWebhookEventQuery) Order(o ...incomingwebhookevent.OrderOption) *IncomingWebhookEventQuery {
	iweq.order = append(iweq.order, o...)
	return iweq
}

// First returns the first IncomingWebhookEvent entity from the query.
// Returns a *NotFoundError when no IncomingWebhookEvent was found.
func (iweq *IncomingWebhookEventQuery) First(ctx context.Context) (*IncomingWebhookEvent, error) {
	nodes, err := iweq.Limit(1).All(setContextOp(ctx, iweq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{incomingwebhookevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (iweq *IncomingWebhookEventQuery) FirstX(ctx context.Context) *IncomingWebhookEvent {
	node, err := iweq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IncomingWebhookEvent ID from the query.
// Returns a *NotFoundError when no IncomingWebhookEvent ID was found.
func (iweq *IncomingWebhookEventQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = iweq.Limit(1).IDs(setContextOp(ctx, iweq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{incomingwebhookevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (iweq *IncomingWebhookEventQuery) FirstIDX(ctx context.Context) string {
	id, err := iweq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IncomingWebhookEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IncomingWebhookEvent entity is found.
// Returns a *NotFoundError when no IncomingWebhookEvent entities are found.
func (iweq *IncomingWebhookEventQuery) Only(ctx context.Context) (*IncomingWebhookEvent, error) {
	nodes, err := iweq.Limit(2).All(setContextOp(ctx, iweq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{incomingwebhookevent.Label}
	default:
		return nil, &NotSingularError{incomingwebhookevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (iweq *IncomingWebhookEventQuery) OnlyX(ctx context.Context) *IncomingWebhookEvent {
	node, err := iweq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IncomingWebhookEvent ID in the query.
// Returns a *NotSingularError when more than one IncomingWebhookEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (iweq *IncomingWebhookEventQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = iweq.Limit(2).IDs(setContextOp(ctx, iweq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{incomingwebhookevent.Label}
	default:
		err = &NotSingularError{incomingwebhookevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (iweq *IncomingWebhookEventQuery) OnlyIDX(ctx context.Context) string {
	id, err := iweq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IncomingWebhookEvents.
func (iweq *IncomingWebhookEventQuery) All(ctx context.Context) ([]*IncomingWebhookEvent, error) {
	ctx = setContextOp(ctx, iweq.ctx, ent.OpQueryAll)
	if err := iweq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IncomingWebhookEvent, *IncomingWebhookEventQuery]()
	return withInterceptors[[]*IncomingWebhookEvent](ctx, iweq, qr, iweq.inters)
}

// AllX is like All, but panics if an error occurs.
func (iweq *IncomingWebhookEventQuery) AllX(ctx context.Context) []*IncomingWebhookEvent {
	nodes, err := iweq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IncomingWebhookEvent IDs.
func (iweq *IncomingWebhookEventQuery) IDs(ctx context.Context) (ids []string, err error) {
	if iweq.ctx.Unique == nil && iweq.path != nil {
		iweq.Unique(true)
	}
	ctx = setContextOp(ctx, iweq.ctx, ent.OpQueryIDs)
	if err = iweq.Select(incomingwebhookevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (iweq *IncomingWebhookEventQuery) IDsX(ctx context.Context) []string {
	ids, err := iweq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (iweq *IncomingWebhookEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, iweq.ctx, ent.OpQueryCount)
	if err := iweq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, iweq, querierCount[*IncomingWebhookEventQuery](), iweq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (iweq *IncomingWebhookEventQuery) CountX(ctx context.Context) int {
	count, err := iweq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (iweq *IncomingWebhookEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, iweq.ctx, ent.OpQueryExist)
	switch _, err := iweq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (iweq *IncomingWebhookEventQuery) ExistX(ctx context.Context) bool {
	exist, err := iweq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IncomingWebhookEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (iweq *IncomingWebhookEventQuery) Clone() *IncomingWebhookEventQuery {
	if iweq == nil {
		return nil
	}
	return &IncomingWebhookEventQuery{
		config:     iweq.config,
		ctx:        iweq.ctx.Clone(),
		order:      append([]incomingwebhookevent.OrderOption{}, iweq.order...),
		inters:     append([]Interceptor{}, iweq.inters...),
		predicates: append([]predicate.IncomingWebhookEvent{}, iweq.predicates...),
		// clone intermediate query.
		sql:  iweq.sql.Clone(),
		path: iweq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IncomingWebhookEvent.Query().
//		GroupBy(incomingwebhookevent.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (iweq *IncomingWebhookEventQuery) GroupBy(field string, fields ...string) *IncomingWebhookEventGroupBy {
	iweq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IncomingWebhookEventGroupBy{build: iweq}
	grbuild.flds = &iweq.ctx.Fields
	grbuild.label = incomingwebhookevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.IncomingWebhookEvent.Query().
//		Select(incomingwebhookevent.FieldTenantID).
//		Scan(ctx, &v)
func (iweq *IncomingWebhookEventQuery) Select(fields ...string) *IncomingWebhookEventSelect {
	iweq.ctx.Fields = append(iweq.ctx.Fields, fields...)
	sbuild := &IncomingWebhookEventSelect{IncomingWebhookEventQuery: iweq}
	sbuild.label = incomingwebhookevent.Label
	sbuild.flds, sbuild.scan = &iweq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IncomingWebhookEventSelect configured with the given aggregations.
func (iweq *IncomingWebhookEventQuery) Aggregate(fns ...AggregateFunc) *IncomingWebhookEventSelect {
	return iweq.Select().Aggregate(fns...)
}

func (iweq *IncomingWebhookEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range iweq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, iweq); err != nil {
				return err
			}
		}
	}
	for _, f := range iweq.ctx.Fields {
		if !incomingwebhookevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if iweq.path != nil {
		prev, err := iweq.path(ctx)
		if err != nil {
			return err
		}
		iweq.sql = prev
	}
	return nil
}

func (iweq *IncomingWebhookEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IncomingWebhookEvent, error) {
	var (
		nodes = []*IncomingWebhookEvent{}
		_spec = iweq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IncomingWebhookEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IncomingWebhookEvent{config: iweq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, iweq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (iweq *IncomingWebhookEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := iweq.querySpec()
	_spec.Node.Columns = iweq.ctx.Fields
	if len(iweq.ctx.Fields) > 0 {
		_spec.Unique = iweq.ctx.Unique != nil && *iweq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, iweq.driver, _spec)
}

func (iweq *IncomingWebhookEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(incomingwebhookevent.Table, incomingwebhookevent.Columns, sqlgraph.NewFieldSpec(incomingwebhookevent.FieldID, field.TypeString))
	_spec.From = iweq.sql
	if unique := iweq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if iweq.path != nil {
		_spec.Unique = true
	}
	if fields := iweq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, incomingwebhookevent.FieldID)
		for i := range fields {
			if fields[i] != incomingwebhookevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := iweq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := iweq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := iweq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := iweq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (iweq *IncomingWebhookEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(iweq.driver.Dialect())
	t1 := builder.Table(incomingwebhookevent.Table)
	columns := iweq.ctx.Fields
	if len(columns) == 0 {
		columns = incomingwebhookevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if iweq.sql != nil {
		selector = iweq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if iweq.ctx.Unique != nil && *iweq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range iweq.predicates {
		p(selector)
	}
	for _, p := range iweq.order {
		p(selector)
	}
	if offset := iweq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := iweq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IncomingWebhookEventGroupBy is the group-by builder for IncomingWebhookEvent entities.
type IncomingWebhookEventGroupBy struct {
	selector
	build *IncomingWebhookEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (iwegb *IncomingWebhookEventGroupBy) Aggregate(fns ...AggregateFunc) *IncomingWebhookEventGroupBy {
	iwegb.fns = append(iwegb.fns, fns...)
	return iwegb
}

// Scan applies the selector query and scans the result into the given value.
func (iwegb *IncomingWebhookEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, iwegb.build.ctx, ent.OpQueryGroupBy)
	if err := iwegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IncomingWebhookEventQuery, *IncomingWebhookEventGroupBy](ctx, iwegb.build, iwegb, iwegb.build.inters, v)
}

func (iwegb *IncomingWebhookEventGroupBy) sqlScan(ctx context.Context, root *IncomingWebhookEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(iwegb.fns))
	for _, fn := range iwegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*iwegb.flds)+len(iwegb.fns))
		for _, f := range *iwegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*iwegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := iwegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IncomingWebhookEventSelect is the builder for selecting fields of IncomingWebhookEvent entities.
type IncomingWebhookEventSelect struct {
	*IncomingWebhookEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (iwes *IncomingWebhookEventSelect) Aggregate(fns ...AggregateFunc) *IncomingWebhookEventSelect {
	iwes.fns = append(iwes.fns, fns...)
	return iwes
}

// Scan applies the selector query and scans the result into the given value.
func (iwes *IncomingWebhookEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, iwes.ctx, ent.OpQuerySelect)
	if err := iwes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IncomingWebhookEventQuery, *IncomingWebhookEventSelect](ctx, iwes.IncomingWebhookEventQuery, iwes, iwes.inters, v)
}

func (iwes *IncomingWebhookEventSelect) sqlScan(ctx context.Context, root *IncomingWebhookEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(iwes.fns))
	for _, fn := range iwes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*iwes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := iwes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
