// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/meterprovidermapping"
	"github.com/flexprice/flexprice/ent/predicate"
)

// MeterProviderMappingQuery is the builder for querying MeterProviderMapping entities.
type MeterProviderMappingQuery struct {
	config
	ctx        *QueryContext
	order      []meterprovidermapping.OrderOption
	inters     []Interceptor
	predicates []predicate.MeterProviderMapping
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MeterProviderMappingQuery builder.
func (mpmq *MeterProviderMappingQuery) Where(ps ...predicate.MeterProviderMapping) *MeterProviderMappingQuery {
	mpmq.predicates = append(mpmq.predicates, ps...)
	return mpmq
}

// Limit the number of records to be returned by this query.
func (mpmq *MeterProviderMappingQuery) Limit(limit int) *MeterProviderMappingQuery {
	mpmq.ctx.Limit = &limit
	return mpmq
}

// Offset to start from.
func (mpmq *MeterProviderMappingQuery) Offset(offset int) *MeterProviderMappingQuery {
	mpmq.ctx.Offset = &offset
	return mpmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mpmq *MeterProviderMappingQuery) Unique(unique bool) *MeterProviderMappingQuery {
	mpmq.ctx.Unique = &unique
	return mpmq
}

// Order specifies how the records should be ordered.
func (mpmq *MeterProviderMappingQuery) Order(o ...meterprovidermapping.OrderOption) *MeterProviderMappingQuery {
	mpmq.order = append(mpmq.order, o...)
	return mpmq
}

// First returns the first MeterProviderMapping entity from the query.
// Returns a *NotFoundError when no MeterProviderMapping was found.
func (mpmq *MeterProviderMappingQuery) First(ctx context.Context) (*MeterProviderMapping, error) {
	nodes, err := mpmq.Limit(1).All(setContextOp(ctx, mpmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{meterprovidermapping.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mpmq *MeterProviderMappingQuery) FirstX(ctx context.Context) *MeterProviderMapping {
	node, err := mpmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MeterProviderMapping ID from the query.
// Returns a *NotFoundError when no MeterProviderMapping ID was found.
func (mpmq *MeterProviderMappingQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = mpmq.Limit(1).IDs(setContextOp(ctx, mpmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{meterprovidermapping.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mpmq *MeterProviderMappingQuery) FirstIDX(ctx context.Context) string {
	id, err := mpmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MeterProviderMapping entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MeterProviderMapping entity is found.
// Returns a *NotFoundError when no MeterProviderMapping entities are found.
func (mpmq *MeterProviderMappingQuery) Only(ctx context.Context) (*MeterProviderMapping, error) {
	nodes, err := mpmq.Limit(2).All(setContextOp(ctx, mpmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{meterprovidermapping.Label}
	default:
		return nil, &NotSingularError{meterprovidermapping.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mpmq *MeterProviderMappingQuery) OnlyX(ctx context.Context) *MeterProviderMapping {
	node, err := mpmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MeterProviderMapping ID in the query.
// Returns a *NotSingularError when more than one MeterProviderMapping ID is found.
// Returns a *NotFoundError when no entities are found.
func (mpmq *MeterProviderMappingQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = mpmq.Limit(2).IDs(setContextOp(ctx, mpmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{meterprovidermapping.Label}
	default:
		err = &NotSingularError{meterprovidermapping.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mpmq *MeterProviderMappingQuery) OnlyIDX(ctx context.Context) string {
	id, err := mpmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MeterProviderMappings.
func (mpmq *MeterProviderMappingQuery) All(ctx context.Context) ([]*MeterProviderMapping, error) {
	ctx = setContextOp(ctx, mpmq.ctx, ent.OpQueryAll)
	if err := mpmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MeterProviderMapping, *MeterProviderMappingQuery]()
	return withInterceptors[[]*MeterProviderMapping](ctx, mpmq, qr, mpmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mpmq *MeterProviderMappingQuery) AllX(ctx context.Context) []*MeterProviderMapping {
	nodes, err := mpmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MeterProviderMapping IDs.
func (mpmq *MeterProviderMappingQuery) IDs(ctx context.Context) (ids []string, err error) {
	if mpmq.ctx.Unique == nil && mpmq.path != nil {
		mpmq.Unique(true)
	}
	ctx = setContextOp(ctx, mpmq.ctx, ent.OpQueryIDs)
	if err = mpmq.Select(meterprovidermapping.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mpmq *MeterProviderMappingQuery) IDsX(ctx context.Context) []string {
	ids, err := mpmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mpmq *MeterProviderMappingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mpmq.ctx, ent.OpQueryCount)
	if err := mpmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mpmq, querierCount[*MeterProviderMappingQuery](), mpmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mpmq *MeterProviderMappingQuery) CountX(ctx context.Context) int {
	count, err := mpmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mpmq *MeterProviderMappingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mpmq.ctx, ent.OpQueryExist)
	switch _, err := mpmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mpmq *MeterProviderMappingQuery) ExistX(ctx context.Context) bool {
	exist, err := mpmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MeterProviderMappingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mpmq *MeterProviderMappingQuery) Clone() *MeterProviderMappingQuery {
	if mpmq == nil {
		return nil
	}
	return &MeterProviderMappingQuery{
		config:     mpmq.config,
		ctx:        mpmq.ctx.Clone(),
		order:      append([]meterprovidermapping.OrderOption{}, mpmq.order...),
		inters:     append([]Interceptor{}, mpmq.inters...),
		predicates: append([]predicate.MeterProviderMapping{}, mpmq.predicates...),
		// clone intermediate query.
		sql:  mpmq.sql.Clone(),
		path: mpmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MeterProviderMapping.Query().
//		GroupBy(meterprovidermapping.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mpmq *MeterProviderMappingQuery) GroupBy(field string, fields ...string) *MeterProviderMappingGroupBy {
	mpmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MeterProviderMappingGroupBy{build: mpmq}
	grbuild.flds = &mpmq.ctx.Fields
	grbuild.label = meterprovidermapping.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.MeterProviderMapping.Query().
//		Select(meterprovidermapping.FieldTenantID).
//		Scan(ctx, &v)
func (mpmq *MeterProviderMappingQuery) Select(fields ...string) *MeterProviderMappingSelect {
	mpmq.ctx.Fields = append(mpmq.ctx.Fields, fields...)
	sbuild := &MeterProviderMappingSelect{MeterProviderMappingQuery: mpmq}
	sbuild.label = meterprovidermapping.Label
	sbuild.flds, sbuild.scan = &mpmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MeterProviderMappingSelect configured with the given aggregations.
func (mpmq *MeterProviderMappingQuery) Aggregate(fns ...AggregateFunc) *MeterProviderMappingSelect {
	return mpmq.Select().Aggregate(fns...)
}

func (mpmq *MeterProviderMappingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mpmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mpmq); err != nil {
				return err
			}
		}
	}
	for _, f := range mpmq.ctx.Fields {
		if !meterprovidermapping.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mpmq.path != nil {
		prev, err := mpmq.path(ctx)
		if err != nil {
			return err
		}
		mpmq.sql = prev
	}
	return nil
}

func (mpmq *MeterProviderMappingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MeterProviderMapping, error) {
	var (
		nodes = []*MeterProviderMapping{}
		_spec = mpmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MeterProviderMapping).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MeterProviderMapping{config: mpmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mpmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mpmq *MeterProviderMappingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mpmq.querySpec()
	_spec.Node.Columns = mpmq.ctx.Fields
	if len(mpmq.ctx.Fields) > 0 {
		_spec.Unique = mpmq.ctx.Unique != nil && *mpmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mpmq.driver, _spec)
}

func (mpmq *MeterProviderMappingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(meterprovidermapping.Table, meterprovidermapping.Columns, sqlgraph.NewFieldSpec(meterprovidermapping.FieldID, field.TypeString))
	_spec.From = mpmq.sql
	if unique := mpmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mpmq.path != nil {
		_spec.Unique = true
	}
	if fields := mpmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, meterprovidermapping.FieldID)
		for i := range fields {
			if fields[i] != meterprovidermapping.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mpmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mpmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mpmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mpmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mpmq *MeterProviderMappingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mpmq.driver.Dialect())
	t1 := builder.Table(meterprovidermapping.Table)
	columns := mpmq.ctx.Fields
	if len(columns) == 0 {
		columns = meterprovidermapping.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mpmq.sql != nil {
		selector = mpmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mpmq.ctx.Unique != nil && *mpmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mpmq.predicates {
		p(selector)
	}
	for _, p := range mpmq.order {
		p(selector)
	}
	if offset := mpmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mpmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MeterProviderMappingGroupBy is the group-by builder for MeterProviderMapping entities.
type MeterProviderMappingGroupBy struct {
	selector
	build *MeterProviderMappingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mpmgb *MeterProviderMappingGroupBy) Aggregate(fns ...AggregateFunc) *MeterProviderMappingGroupBy {
	mpmgb.fns = append(mpmgb.fns, fns...)
	return mpmgb
}

// Scan applies the selector query and scans the result into the given value.
func (mpmgb *MeterProviderMappingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mpmgb.build.ctx, ent.OpQueryGroupBy)
	if err := mpmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MeterProviderMappingQuery, *MeterProviderMappingGroupBy](ctx, mpmgb.build, mpmgb, mpmgb.build.inters, v)
}

func (mpmgb *MeterProviderMappingGroupBy) sqlScan(ctx context.Context, root *MeterProviderMappingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mpmgb.fns))
	for _, fn := range mpmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mpmgb.flds)+len(mpmgb.fns))
		for _, f := range *mpmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mpmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mpmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MeterProviderMappingSelect is the builder for selecting fields of MeterProviderMapping entities.
type MeterProviderMappingSelect struct {
	*MeterProviderMappingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mpms *MeterProviderMappingSelect) Aggregate(fns ...AggregateFunc) *MeterProviderMappingSelect {
	mpms.fns = append(mpms.fns, fns...)
	return mpms
}

// Scan applies the selector query and scans the result into the given value.
func (mpms *MeterProviderMappingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mpms.ctx, ent.OpQuerySelect)
	if err := mpms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MeterProviderMappingQuery, *MeterProviderMappingSelect](ctx, mpms.MeterProviderMappingQuery, mpms, mpms.inters, v)
}

func (mpms *MeterProviderMappingSelect) sqlScan(ctx context.Context, root *MeterProviderMappingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mpms.fns))
	for _, fn := range mpms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mpms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mpms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
