// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/paymentmethod"
	"github.com/flexprice/flexprice/internal/types"
)

// PaymentMethod is the model entity for the PaymentMethod schema.
type PaymentMethod struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// EnvironmentID holds the value of the "environment_id" field.
	EnvironmentID string `json:"environment_id,omitempty"`
	// CustomerID holds the value of the "customer_id" field.
	CustomerID string `json:"customer_id,omitempty"`
	// Type holds the value of the "type" field.
	Type types.PaymentMethodType `json:"type,omitempty"`
	// Gateway holds the value of the "gateway" field.
	Gateway types.PaymentGatewayType `json:"gateway,omitempty"`
	// GatewayMethodID holds the value of the "gateway_method_id" field.
	GatewayMethodID string `json:"gateway_method_id,omitempty"`
	// PaymentMethodStatus holds the value of the "payment_method_status" field.
	PaymentMethodStatus types.PaymentMethodStatus `json:"payment_method_status,omitempty"`
	// IsDefault holds the value of the "is_default" field.
	IsDefault bool `json:"is_default,omitempty"`
	// MethodDetails holds the value of the "method_details" field.
	MethodDetails map[string]interface{} `json:"method_details,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentMethod) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentmethod.FieldMethodDetails:
			values[i] = new([]byte)
		case paymentmethod.FieldIsDefault:
			values[i] = new(sql.NullBool)
		case paymentmethod.FieldID, paymentmethod.FieldTenantID, paymentmethod.FieldStatus, paymentmethod.FieldCreatedBy, paymentmethod.FieldUpdatedBy, paymentmethod.FieldEnvironmentID, paymentmethod.FieldCustomerID, paymentmethod.FieldType, paymentmethod.FieldGateway, paymentmethod.FieldGatewayMethodID, paymentmethod.FieldPaymentMethodStatus:
			values[i] = new(sql.NullString)
		case paymentmethod.FieldCreatedAt, paymentmethod.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentMethod fields.
func (pm *PaymentMethod) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentmethod.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				pm.ID = value.String
			}
		case paymentmethod.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				pm.TenantID = value.String
			}
		case paymentmethod.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				pm.Status = value.String
			}
		case paymentmethod.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pm.CreatedAt = value.Time
			}
		case paymentmethod.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pm.UpdatedAt = value.Time
			}
		case paymentmethod.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				pm.CreatedBy = value.String
			}
		case paymentmethod.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				pm.UpdatedBy = value.String
			}
		case paymentmethod.FieldEnvironmentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment_id", values[i])
			} else if value.Valid {
				pm.EnvironmentID = value.String
			}
		case paymentmethod.FieldCustomerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_id", values[i])
			} else if value.Valid {
				pm.CustomerID = value.String
			}
		case paymentmethod.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				pm.Type = types.PaymentMethodType(value.String)
			}
		case paymentmethod.FieldGateway:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gateway", values[i])
			} else if value.Valid {
				pm.Gateway = types.PaymentGatewayType(value.String)
			}
		case paymentmethod.FieldGatewayMethodID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_method_id", values[i])
			} else if value.Valid {
				pm.GatewayMethodID = value.String
			}
		case paymentmethod.FieldPaymentMethodStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_method_status", values[i])
			} else if value.Valid {
				pm.PaymentMethodStatus = types.PaymentMethodStatus(value.String)
			}
		case paymentmethod.FieldIsDefault:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_default", values[i])
			} else if value.Valid {
				pm.IsDefault = value.Bool
			}
		case paymentmethod.FieldMethodDetails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field method_details", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &pm.MethodDetails); err != nil {
					return fmt.Errorf("unmarshal field method_details: %w", err)
				}
			}
		default:
			pm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentMethod.
// This includes values selected through modifiers, order, etc.
func (pm *PaymentMethod) Value(name string) (ent.Value, error) {
	return pm.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentMethod.
// Note that you need to call PaymentMethod.Unwrap() before calling this method if this PaymentMethod
// was returned from a transaction, and the transaction was committed or rolled back.
func (pm *PaymentMethod) Update() *PaymentMethodUpdateOne {
	return NewPaymentMethodClient(pm.config).UpdateOne(pm)
}

// Unwrap unwraps the PaymentMethod entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pm *PaymentMethod) Unwrap() *PaymentMethod {
	_tx, ok := pm.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentMethod is not a transactional entity")
	}
	pm.config.driver = _tx.drv
	return pm
}

// String implements the fmt.Stringer.
func (pm *PaymentMethod) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentMethod(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pm.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(pm.TenantID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(pm.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pm.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(pm.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(pm.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(pm.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("environment_id=")
	builder.WriteString(pm.EnvironmentID)
	builder.WriteString(", ")
	builder.WriteString("customer_id=")
	builder.WriteString(pm.CustomerID)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", pm.Type))
	builder.WriteString(", ")
	builder.WriteString("gateway=")
	builder.WriteString(fmt.Sprintf("%v", pm.Gateway))
	builder.WriteString(", ")
	builder.WriteString("gateway_method_id=")
	builder.WriteString(pm.GatewayMethodID)
	builder.WriteString(", ")
	builder.WriteString("payment_method_status=")
	builder.WriteString(fmt.Sprintf("%v", pm.PaymentMethodStatus))
	builder.WriteString(", ")
	builder.WriteString("is_default=")
	builder.WriteString(fmt.Sprintf("%v", pm.IsDefault))
	builder.WriteString(", ")
	builder.WriteString("method_details=")
	builder.WriteString(fmt.Sprintf("%v", pm.MethodDetails))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentMethods is a parsable slice of PaymentMethod.
type PaymentMethods []*PaymentMethod
