// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/ent/stripetenantconfig"
)

// StripeTenantConfigQuery is the builder for querying StripeTenantConfig entities.
type StripeTenantConfigQuery struct {
	config
	ctx        *QueryContext
	order      []stripetenantconfig.OrderOption
	inters     []Interceptor
	predicates []predicate.StripeTenantConfig
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StripeTenantConfigQuery builder.
func (stcq *StripeTenantConfigQuery) Where(ps ...predicate.StripeTenantConfig) *StripeTenantConfigQuery {
	stcq.predicates = append(stcq.predicates, ps...)
	return stcq
}

// Limit the number of records to be returned by this query.
func (stcq *StripeTenantConfigQuery) Limit(limit int) *StripeTenantConfigQuery {
	stcq.ctx.Limit = &limit
	return stcq
}

// Offset to start from.
func (stcq *StripeTenantConfigQuery) Offset(offset int) *StripeTenantConfigQuery {
	stcq.ctx.Offset = &offset
	return stcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (stcq *StripeTenantConfigQuery) Unique(unique bool) *StripeTenantConfigQuery {
	stcq.ctx.Unique = &unique
	return stcq
}

// Order specifies how the records should be ordered.
func (stcq *StripeTenantConfigQuery) Order(o ...stripetenantconfig.OrderOption) *StripeTenantConfigQuery {
	stcq.order = append(stcq.order, o...)
	return stcq
}

// First returns the first StripeTenantConfig entity from the query.
// Returns a *NotFoundError when no StripeTenantConfig was found.
func (stcq *StripeTenantConfigQuery) First(ctx context.Context) (*StripeTenantConfig, error) {
	nodes, err := stcq.Limit(1).All(setContextOp(ctx, stcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{stripetenantconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (stcq *StripeTenantConfigQuery) FirstX(ctx context.Context) *StripeTenantConfig {
	node, err := stcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StripeTenantConfig ID from the query.
// Returns a *NotFoundError when no StripeTenantConfig ID was found.
func (stcq *StripeTenantConfigQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = stcq.Limit(1).IDs(setContextOp(ctx, stcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{stripetenantconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (stcq *StripeTenantConfigQuery) FirstIDX(ctx context.Context) string {
	id, err := stcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StripeTenantConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StripeTenantConfig entity is found.
// Returns a *NotFoundError when no StripeTenantConfig entities are found.
func (stcq *StripeTenantConfigQuery) Only(ctx context.Context) (*StripeTenantConfig, error) {
	nodes, err := stcq.Limit(2).All(setContextOp(ctx, stcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{stripetenantconfig.Label}
	default:
		return nil, &NotSingularError{stripetenantconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (stcq *StripeTenantConfigQuery) OnlyX(ctx context.Context) *StripeTenantConfig {
	node, err := stcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StripeTenantConfig ID in the query.
// Returns a *NotSingularError when more than one StripeTenantConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (stcq *StripeTenantConfigQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = stcq.Limit(2).IDs(setContextOp(ctx, stcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{stripetenantconfig.Label}
	default:
		err = &NotSingularError{stripetenantconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (stcq *StripeTenantConfigQuery) OnlyIDX(ctx context.Context) string {
	id, err := stcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StripeTenantConfigs.
func (stcq *StripeTenantConfigQuery) All(ctx context.Context) ([]*StripeTenantConfig, error) {
	ctx = setContextOp(ctx, stcq.ctx, ent.OpQueryAll)
	if err := stcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StripeTenantConfig, *StripeTenantConfigQuery]()
	return withInterceptors[[]*StripeTenantConfig](ctx, stcq, qr, stcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (stcq *StripeTenantConfigQuery) AllX(ctx context.Context) []*StripeTenantConfig {
	nodes, err := stcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StripeTenantConfig IDs.
func (stcq *StripeTenantConfigQuery) IDs(ctx context.Context) (ids []string, err error) {
	if stcq.ctx.Unique == nil && stcq.path != nil {
		stcq.Unique(true)
	}
	ctx = setContextOp(ctx, stcq.ctx, ent.OpQueryIDs)
	if err = stcq.Select(stripetenantconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (stcq *StripeTenantConfigQuery) IDsX(ctx context.Context) []string {
	ids, err := stcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (stcq *StripeTenantConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, stcq.ctx, ent.OpQueryCount)
	if err := stcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, stcq, querierCount[*StripeTenantConfigQuery](), stcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (stcq *StripeTenantConfigQuery) CountX(ctx context.Context) int {
	count, err := stcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (stcq *StripeTenantConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, stcq.ctx, ent.OpQueryExist)
	switch _, err := stcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (stcq *StripeTenantConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := stcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StripeTenantConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (stcq *StripeTenantConfigQuery) Clone() *StripeTenantConfigQuery {
	if stcq == nil {
		return nil
	}
	return &StripeTenantConfigQuery{
		config:     stcq.config,
		ctx:        stcq.ctx.Clone(),
		order:      append([]stripetenantconfig.OrderOption{}, stcq.order...),
		inters:     append([]Interceptor{}, stcq.inters...),
		predicates: append([]predicate.StripeTenantConfig{}, stcq.predicates...),
		// clone intermediate query.
		sql:  stcq.sql.Clone(),
		path: stcq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StripeTenantConfig.Query().
//		GroupBy(stripetenantconfig.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (stcq *StripeTenantConfigQuery) GroupBy(field string, fields ...string) *StripeTenantConfigGroupBy {
	stcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StripeTenantConfigGroupBy{build: stcq}
	grbuild.flds = &stcq.ctx.Fields
	grbuild.label = stripetenantconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.StripeTenantConfig.Query().
//		Select(stripetenantconfig.FieldTenantID).
//		Scan(ctx, &v)
func (stcq *StripeTenantConfigQuery) Select(fields ...string) *StripeTenantConfigSelect {
	stcq.ctx.Fields = append(stcq.ctx.Fields, fields...)
	sbuild := &StripeTenantConfigSelect{StripeTenantConfigQuery: stcq}
	sbuild.label = stripetenantconfig.Label
	sbuild.flds, sbuild.scan = &stcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StripeTenantConfigSelect configured with the given aggregations.
func (stcq *StripeTenantConfigQuery) Aggregate(fns ...AggregateFunc) *StripeTenantConfigSelect {
	return stcq.Select().Aggregate(fns...)
}

func (stcq *StripeTenantConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range stcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, stcq); err != nil {
				return err
			}
		}
	}
	for _, f := range stcq.ctx.Fields {
		if !stripetenantconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if stcq.path != nil {
		prev, err := stcq.path(ctx)
		if err != nil {
			return err
		}
		stcq.sql = prev
	}
	return nil
}

func (stcq *StripeTenantConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StripeTenantConfig, error) {
	var (
		nodes = []*StripeTenantConfig{}
		_spec = stcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StripeTenantConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StripeTenantConfig{config: stcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, stcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (stcq *StripeTenantConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := stcq.querySpec()
	_spec.Node.Columns = stcq.ctx.Fields
	if len(stcq.ctx.Fields) > 0 {
		_spec.Unique = stcq.ctx.Unique != nil && *stcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, stcq.driver, _spec)
}

func (stcq *StripeTenantConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(stripetenantconfig.Table, stripetenantconfig.Columns, sqlgraph.NewFieldSpec(stripetenantconfig.FieldID, field.TypeString))
	_spec.From = stcq.sql
	if unique := stcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if stcq.path != nil {
		_spec.Unique = true
	}
	if fields := stcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stripetenantconfig.FieldID)
		for i := range fields {
			if fields[i] != stripetenantconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := stcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := stcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := stcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := stcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (stcq *StripeTenantConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(stcq.driver.Dialect())
	t1 := builder.Table(stripetenantconfig.Table)
	columns := stcq.ctx.Fields
	if len(columns) == 0 {
		columns = stripetenantconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if stcq.sql != nil {
		selector = stcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if stcq.ctx.Unique != nil && *stcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range stcq.predicates {
		p(selector)
	}
	for _, p := range stcq.order {
		p(selector)
	}
	if offset := stcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := stcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StripeTenantConfigGroupBy is the group-by builder for StripeTenantConfig entities.
type StripeTenantConfigGroupBy struct {
	selector
	build *StripeTenantConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (stcgb *StripeTenantConfigGroupBy) Aggregate(fns ...AggregateFunc) *StripeTenantConfigGroupBy {
	stcgb.fns = append(stcgb.fns, fns...)
	return stcgb
}

// Scan applies the selector query and scans the result into the given value.
func (stcgb *StripeTenantConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, stcgb.build.ctx, ent.OpQueryGroupBy)
	if err := stcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StripeTenantConfigQuery, *StripeTenantConfigGroupBy](ctx, stcgb.build, stcgb, stcgb.build.inters, v)
}

func (stcgb *StripeTenantConfigGroupBy) sqlScan(ctx context.Context, root *StripeTenantConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(stcgb.fns))
	for _, fn := range stcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*stcgb.flds)+len(stcgb.fns))
		for _, f := range *stcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*stcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := stcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StripeTenantConfigSelect is the builder for selecting fields of StripeTenantConfig entities.
type StripeTenantConfigSelect struct {
	*StripeTenantConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (stcs *StripeTenantConfigSelect) Aggregate(fns ...AggregateFunc) *StripeTenantConfigSelect {
	stcs.fns = append(stcs.fns, fns...)
	return stcs
}

// Scan applies the selector query and scans the result into the given value.
func (stcs *StripeTenantConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, stcs.ctx, ent.OpQuerySelect)
	if err := stcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StripeTenantConfigQuery, *StripeTenantConfigSelect](ctx, stcs.StripeTenantConfigQuery, stcs, stcs.inters, v)
}

func (stcs *StripeTenantConfigSelect) sqlScan(ctx context.Context, root *StripeTenantConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(stcs.fns))
	for _, fn := range stcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*stcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := stcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
