// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/ent/webhookrequest"
)

// WebhookRequestQuery is the builder for querying WebhookRequest entities.
type WebhookRequestQuery struct {
	config
	ctx        *QueryContext
	order      []webhookrequest.OrderOption
	inters     []Interceptor
	predicates []predicate.WebhookRequest
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WebhookRequestQuery builder.
func (wrq *WebhookRequestQuery) Where(ps ...predicate.WebhookRequest) *WebhookRequestQuery {
	wrq.predicates = append(wrq.predicates, ps...)
	return wrq
}

// Limit the number of records to be returned by this query.
func (wrq *WebhookRequestQuery) Limit(limit int) *WebhookRequestQuery {
	wrq.ctx.Limit = &limit
	return wrq
}

// Offset to start from.
func (wrq *WebhookRequestQuery) Offset(offset int) *WebhookRequestQuery {
	wrq.ctx.Offset = &offset
	return wrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wrq *WebhookRequestQuery) Unique(unique bool) *WebhookRequestQuery {
	wrq.ctx.Unique = &unique
	return wrq
}

// Order specifies how the records should be ordered.
func (wrq *WebhookRequestQuery) Order(o ...webhookrequest.OrderOption) *WebhookRequestQuery {
	wrq.order = append(wrq.order, o...)
	return wrq
}

// First returns the first WebhookRequest entity from the query.
// Returns a *NotFoundError when no WebhookRequest was found.
func (wrq *WebhookRequestQuery) First(ctx context.Context) (*WebhookRequest, error) {
	nodes, err := wrq.Limit(1).All(setContextOp(ctx, wrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{webhookrequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wrq *WebhookRequestQuery) FirstX(ctx context.Context) *WebhookRequest {
	node, err := wrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WebhookRequest ID from the query.
// Returns a *NotFoundError when no WebhookRequest ID was found.
func (wrq *WebhookRequestQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = wrq.Limit(1).IDs(setContextOp(ctx, wrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{webhookrequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wrq *WebhookRequestQuery) FirstIDX(ctx context.Context) string {
	id, err := wrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WebhookRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WebhookRequest entity is found.
// Returns a *NotFoundError when no WebhookRequest entities are found.
func (wrq *WebhookRequestQuery) Only(ctx context.Context) (*WebhookRequest, error) {
	nodes, err := wrq.Limit(2).All(setContextOp(ctx, wrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{webhookrequest.Label}
	default:
		return nil, &NotSingularError{webhookrequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wrq *WebhookRequestQuery) OnlyX(ctx context.Context) *WebhookRequest {
	node, err := wrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WebhookRequest ID in the query.
// Returns a *NotSingularError when more than one WebhookRequest ID is found.
// Returns a *NotFoundError when no entities are found.
func (wrq *WebhookRequestQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = wrq.Limit(2).IDs(setContextOp(ctx, wrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{webhookrequest.Label}
	default:
		err = &NotSingularError{webhookrequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wrq *WebhookRequestQuery) OnlyIDX(ctx context.Context) string {
	id, err := wrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WebhookRequests.
func (wrq *WebhookRequestQuery) All(ctx context.Context) ([]*WebhookRequest, error) {
	ctx = setContextOp(ctx, wrq.ctx, ent.OpQueryAll)
	if err := wrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WebhookRequest, *WebhookRequestQuery]()
	return withInterceptors[[]*WebhookRequest](ctx, wrq, qr, wrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wrq *WebhookRequestQuery) AllX(ctx context.Context) []*WebhookRequest {
	nodes, err := wrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WebhookRequest IDs.
func (wrq *WebhookRequestQuery) IDs(ctx context.Context) (ids []string, err error) {
	if wrq.ctx.Unique == nil && wrq.path != nil {
		wrq.Unique(true)
	}
	ctx = setContextOp(ctx, wrq.ctx, ent.OpQueryIDs)
	if err = wrq.Select(webhookrequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wrq *WebhookRequestQuery) IDsX(ctx context.Context) []string {
	ids, err := wrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wrq *WebhookRequestQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wrq.ctx, ent.OpQueryCount)
	if err := wrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wrq, querierCount[*WebhookRequestQuery](), wrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wrq *WebhookRequestQuery) CountX(ctx context.Context) int {
	count, err := wrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wrq *WebhookRequestQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wrq.ctx, ent.OpQueryExist)
	switch _, err := wrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wrq *WebhookRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := wrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WebhookRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wrq *WebhookRequestQuery) Clone() *WebhookRequestQuery {
	if wrq == nil {
		return nil
	}
	return &WebhookRequestQuery{
		config:     wrq.config,
		ctx:        wrq.ctx.Clone(),
		order:      append([]webhookrequest.OrderOption{}, wrq.order...),
		inters:     append([]Interceptor{}, wrq.inters...),
		predicates: append([]predicate.WebhookRequest{}, wrq.predicates...),
		// clone intermediate query.
		sql:  wrq.sql.Clone(),
		path: wrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WebhookRequest.Query().
//		GroupBy(webhookrequest.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wrq *WebhookRequestQuery) GroupBy(field string, fields ...string) *WebhookRequestGroupBy {
	wrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WebhookRequestGroupBy{build: wrq}
	grbuild.flds = &wrq.ctx.Fields
	grbuild.label = webhookrequest.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.WebhookRequest.Query().
//		Select(webhookrequest.FieldTenantID).
//		Scan(ctx, &v)
func (wrq *WebhookRequestQuery) Select(fields ...string) *WebhookRequestSelect {
	wrq.ctx.Fields = append(wrq.ctx.Fields, fields...)
	sbuild := &WebhookRequestSelect{WebhookRequestQuery: wrq}
	sbuild.label = webhookrequest.Label
	sbuild.flds, sbuild.scan = &wrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WebhookRequestSelect configured with the given aggregations.
func (wrq *WebhookRequestQuery) Aggregate(fns ...AggregateFunc) *WebhookRequestSelect {
	return wrq.Select().Aggregate(fns...)
}

func (wrq *WebhookRequestQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wrq); err != nil {
				return err
			}
		}
	}
	for _, f := range wrq.ctx.Fields {
		if !webhookrequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wrq.path != nil {
		prev, err := wrq.path(ctx)
		if err != nil {
			return err
		}
		wrq.sql = prev
	}
	return nil
}

func (wrq *WebhookRequestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WebhookRequest, error) {
	var (
		nodes = []*WebhookRequest{}
		_spec = wrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WebhookRequest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WebhookRequest{config: wrq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (wrq *WebhookRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wrq.querySpec()
	_spec.Node.Columns = wrq.ctx.Fields
	if len(wrq.ctx.Fields) > 0 {
		_spec.Unique = wrq.ctx.Unique != nil && *wrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wrq.driver, _spec)
}

func (wrq *WebhookRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(webhookrequest.Table, webhookrequest.Columns, sqlgraph.NewFieldSpec(webhookrequest.FieldID, field.TypeString))
	_spec.From = wrq.sql
	if unique := wrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wrq.path != nil {
		_spec.Unique = true
	}
	if fields := wrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webhookrequest.FieldID)
		for i := range fields {
			if fields[i] != webhookrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wrq *WebhookRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wrq.driver.Dialect())
	t1 := builder.Table(webhookrequest.Table)
	columns := wrq.ctx.Fields
	if len(columns) == 0 {
		columns = webhookrequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wrq.sql != nil {
		selector = wrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wrq.ctx.Unique != nil && *wrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wrq.predicates {
		p(selector)
	}
	for _, p := range wrq.order {
		p(selector)
	}
	if offset := wrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WebhookRequestGroupBy is the group-by builder for WebhookRequest entities.
type WebhookRequestGroupBy struct {
	selector
	build *WebhookRequestQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wrgb *WebhookRequestGroupBy) Aggregate(fns ...AggregateFunc) *WebhookRequestGroupBy {
	wrgb.fns = append(wrgb.fns, fns...)
	return wrgb
}

// Scan applies the selector query and scans the result into the given value.
func (wrgb *WebhookRequestGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wrgb.build.ctx, ent.OpQueryGroupBy)
	if err := wrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WebhookRequestQuery, *WebhookRequestGroupBy](ctx, wrgb.build, wrgb, wrgb.build.inters, v)
}

func (wrgb *WebhookRequestGroupBy) sqlScan(ctx context.Context, root *WebhookRequestQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wrgb.fns))
	for _, fn := range wrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wrgb.flds)+len(wrgb.fns))
		for _, f := range *wrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WebhookRequestSelect is the builder for selecting fields of WebhookRequest entities.
type WebhookRequestSelect struct {
	*WebhookRequestQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wrs *WebhookRequestSelect) Aggregate(fns ...AggregateFunc) *WebhookRequestSelect {
	wrs.fns = append(wrs.fns, fns...)
	return wrs
}

// Scan applies the selector query and scans the result into the given value.
func (wrs *WebhookRequestSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wrs.ctx, ent.OpQuerySelect)
	if err := wrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WebhookRequestQuery, *WebhookRequestSelect](ctx, wrs.WebhookRequestQuery, wrs, wrs.inters, v)
}

func (wrs *WebhookRequestSelect) sqlScan(ctx context.Context, root *WebhookRequestQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wrs.fns))
	for _, fn := range wrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
