server:
  address: ":8080"

kafka:
  brokers:
    - "localhost:29092"
  consumerGroup: "flexprice-consumer"
  topic: "events"

clickhouse:
  address: 127.0.0.1:9000
  tls: false
  username: default
  password: default
  database: flexprice

logging:
  level: "debug"

meters:
  - id: "meter1"
    aggregationType: "sum"
    windowSize: "1m"
