deployment:
  mode: "local"

server:
  address: ":8080"

kafka:
  brokers:
    - "localhost:29092"
  consumer_group: "flexprice-consumer-local"
  topic: "events"
  use_sasl: false
  sasl_mechanism: ""
  sasl_user: ""
  sasl_password: ""
  client_id: "flexprice-client-local"

clickhouse:
  address: 127.0.0.1:9000
  tls: false
  username: default
  password: default
  database: flexprice

postgres:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres
  dbname: flexprice
  sslmode: disable

logging:
  level: "debug"

