deployment:
  mode: "local"

server:
  address: ":8080"

auth:
  provider: "flexprice" # "flexprice" or "supabase"
  secret: "031f6bbed1156eca651d48652c17a5bce727514cc804f185aca207153b2915abb79c0f1b53945915866dc3b63f37ea73aa86fc062f13e6008249e30819f87483"
  supabase:
    base_url: "http://localhost:54321"

kafka:
  brokers:
    - "localhost:29092"
  consumer_group: "flexprice-consumer-local"
  topic: "events"
  use_sasl: false
  sasl_mechanism: ""
  sasl_user: ""
  sasl_password: ""
  client_id: "flexprice-client-local"

clickhouse:
  address: 127.0.0.1:9000
  tls: false
  username: default
  password: default
  database: flexprice

postgres:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres
  dbname: flexprice
  sslmode: disable

logging:
  level: "debug"

