apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flexprice.fullname" . }}-secrets
  labels:
    {{- include "flexprice.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ required "A valid .Values.postgres.password is required!" .Values.postgres.password | quote }}
  clickhouse-password: {{ required "A valid .Values.clickhouse.password is required!" .Values.clickhouse.password | quote }}
  auth-secret: {{ required "A valid .Values.auth.secret is required!" .Values.auth.secret | quote }}
  encryption-key: {{ required "A valid .Values.secrets.encryptionKey is required!" .Values.secrets.encryptionKey | quote }}
  {{- if and (eq .Values.auth.provider "supabase") .Values.auth.supabase.serviceKey }}
  supabase-service-key: {{ .Values.auth.supabase.serviceKey | quote }}
  {{- end }}
  {{- if and .Values.kafka.useSASL .Values.kafka.saslPassword }}
  kafka-sasl-password: {{ .Values.kafka.saslPassword | quote }}
  {{- end }}
  {{- if .Values.temporal.apiKey }}
  temporal-api-key: {{ .Values.temporal.apiKey | quote }}
  {{- end }}
  {{- if and .Values.sentry.enabled .Values.sentry.dsn }}
  sentry-dsn: {{ .Values.sentry.dsn | quote }}
  {{- end }}
  {{- if and .Values.pyroscope.enabled .Values.pyroscope.basicAuthPassword }}
  pyroscope-basic-auth-password: {{ .Values.pyroscope.basicAuthPassword | quote }}
  {{- end }}
  {{- if and .Values.email.enabled .Values.email.resendApiKey }}
  email-resend-api-key: {{ .Values.email.resendApiKey | quote }}
  {{- end }}
  {{- if and .Values.webhook.enabled .Values.webhook.svixConfig.enabled .Values.webhook.svixConfig.authToken }}
  svix-auth-token: {{ .Values.webhook.svixConfig.authToken | quote }}
  {{- end }}

