name: Run Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: |
          make test

  lint:
    name: Run Loglint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Build loglint
        run: cd tools/loglint && go mod download && go build -o ../bin/loglint ./main.go

      - name: Run loglint
        run: go vet -vettool=./tools/bin/loglint ./internal/...
